### ISSUE TITLE
ObjectDisposedException thrown when generating JWT in docker container

### ISSUE THREAD

**Issue by lucasecdb** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1002]
Hello, I'm trying to create a docker container with my API, but when I try to login and create a JWT by calling `JwtSecurityTokenHandler.CreateToken`, I get the following exception:

```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Crypto.RsaSize(SafeRsaHandle rsa)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Boolean allocateSignature, Int32& bytesWritten, Byte[]& signature)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSACryptoServiceProvider.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
```

I've created a [sample project](https://github.com/lucasecdb/webapi-jwt-project) with the dockerfile and configurations from my WebApi which is throwing the error.

I think all the configurations and versions should be listed in the csproj of the sample project, but if you need more information about it, just ask :-)

**Comment by CBaud** [comment]
Hey @lucasecdb,

After reviewing your sample project, I believe the root cause of your issue is the 'using' statement that starts on line 28 of the SigningConfigurations class. The benefit of the 'using' statement is that it provides a convenient syntax that ensures the correct use of IDisposable objects. As a result, the RSACryptoServiceProvider instance is getting disposed immediately after it is used to initialize the RsaSecurityKey instance. In order for the JwtSecurityTokenHandler to use an RsaSecurityKey to create a digital signature for the JWT, it needs an RSACryptoServiceProvider instance that has not already been disposed.

I would recommend that the SigningConfigurations class be updated to utilize the [Dispose Pattern](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) instead of encapsulating the RSACryptoServiceProvider within the scope of a 'using' statement.

**Comment by lucasecdb** [comment]
@CBaud that was it! Thank you so much for the help :-)
