### ISSUE TITLE
Null reference encountered when validating a token with no 'aud' claim

### ISSUE THREAD

**Issue by ghakazian** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1024]
I am trying to validate some custom generated tokens which do not include the audience claim, which per RFC 7519 is an optional claim. When attempting to validate the tokens without audience set, I get a NullReferenceException from JsonWebToken.get_Audiences().
The expected behavior is that I can validate the token without an audience by setting ValidateAudience=false on the validation parameters object.

This was encountered in version 5.2.4 on .NET Core 2.1

```
           // Create signing credential
            var rng = RandomNumberGenerator.Create();
            var bytes = new byte[256];
            rng.GetBytes(bytes);
            var key = new SymmetricSecurityKey(bytes);
            
            // Create sample token payload
            var payload = new JObject();
            var iat = new DateTimeOffset(DateTime.Now).ToUnixTimeSeconds();
            payload.Add("iss", "localhost");
            payload.Add("iat", iat);
            payload.Add("exp", iat + 300); // Expires in 5 minutes
            payload.Add("preferred_username", "testuser");
            payload.Add("sub", "1000");
            payload.Add("jti", Guid.NewGuid().ToString());

            // Create the token
            var handler = new JsonWebTokenHandler();
            var token = handler.CreateToken(payload, new SigningCredentials(key, SecurityAlgorithms.HmacSha256Signature));

            // Validate the token
            var parms = new TokenValidationParameters();
            parms.ValidateAudience = false;
            parms.ValidateIssuer = false;
            parms.IssuerSigningKey = key;
            var result = handler.ValidateToken(token, parms);
```
```
authsvc.Tests.UtilitiesTests.TestSimpleTokenValidation:
    Outcome: Failed
    Error Message:
    System.NullReferenceException : Object reference not set to an instance of an object.
    Stack Trace:
       at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.get_Audiences() in C:\agent2\_work\15\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebToken.cs:line 113
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateTokenPayload(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters) in C:\agent2\_work\15\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebTokenHandler.cs:line 414
   at authsvc.Tests.UtilitiesTests.TestSimpleTokenValidation() in c:\Users\brooksm\source\repos\mnode-svc-auth\authsvc.Tests\UtilitiesTests.cs:line 55
```

**Comment by brentschmaltz** [comment]
@ghakazian sorry we let that slip through. We are pushing up 5.3.0 shortly and this has been fixed. The release is currently published on myget here: https://www.myget.org/feed/azureadwebstacknightly/package/nuget/Microsoft.IdentityModel.JsonWebTokens 
The breaking change that removes JObject as a parameter will affect you.
We want to have API's that only depend on .NET Core so to improve backwards compatibility.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases.

**Comment by ghakazian** [comment]
This is perfect, I will look for 5.3.0 shortly. Thanks.
