### ISSUE TITLE
JwtSecurityTokenHandler.WriteToken fails in Azure HTTP Trigger function

### ISSUE THREAD

**Issue by iwaldman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1081]
Get error "The system cannot find the file specified" when invoking JwtSecurityTokenHandler.WriteToken in an Azure HTTP Trigger function.

2018-12-18T16:29:55.432 [Error] Exception -2147024894 The system cannot find the file specified (null)    at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKeyStatus()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.FoundPrivateKey(SecurityKey key)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at D365JWTFuncApp2.D365JWTHttpTrigger.CreateJWT5(ILogger log) in C:\d365\D365JWTFuncApp\D365JWTFuncApp2\D365JWTHttpTrigger.cs:line 370

```
       static string CreateJWT5(ILogger log)
        {
            try
            {
                var audience = "https://login.cloud.com";
                var tenantId = "15dc65f8-f9ef-4133-af64-dce5bd1f1324";
                var issuer = "urn:pros:portal:acct:" + "c3124cd5-c250-480f-8ef1-70515dba9cd9";
                var scope = "urn:pros:portal:app:" + "d363cfa0-14b0-4224-a0f7-653f0fc29d63";

                var utc0 = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
                var issueTime = DateTime.UtcNow;

                var iat = (Int64)issueTime.Subtract(utc0).TotalSeconds;
                var exp = (Int64)issueTime.AddMinutes(55).Subtract(utc0).TotalSeconds;

                X509SecurityKey signingKey = KeyingMaterial.X509SecurityKeySelfSigned2048_SHA256;
                var signingCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.RsaSha256Signature);

                var header = new JwtHeader(signingCredentials);
                header.Clear();
                header.Add("alg", "RS256");
                header.Add("typ", "JWT");

                var payload = new JwtPayload(
                    issuer,
                    audience,
                    new List<Claim>() {
                        new Claim("tid", tenantId),
                        new Claim("scope", scope),
                        new Claim(JwtRegisteredClaimNames.Iat, iat.ToString(), ClaimValueTypes.Integer64),
                        new Claim(JwtRegisteredClaimNames.Exp, exp.ToString(), ClaimValueTypes.Integer64)
                    },
                    null,
                    null
                );

                var jwtToken = new JwtSecurityToken(header, payload);
                var handler = new JwtSecurityTokenHandler();

                log.LogInformation("Calling WriteToken");

               // FAILS HERE
                var jwt = handler.WriteToken(jwtToken);

                log.LogInformation(String.Format("Access Token {0}", jwt));

                return jwt;
            }
            catch (Exception ex)
            {
                log.LogError("Exception {0} {1} {2} {3}", ex.HResult, ex.Message, ex.InnerException, ex.StackTrace);
            }
            return null;
        } 
```

**Comment by GeoK** [comment]
Hi @iwaldman - Where are you getting the _X509SecurityKeySelfSigned2048_SHA256_ from?
I'm guessing that this is a permission issue. Try specifying the _X509KeyStorageFlags.MachineKeySet_ flag.

```csharp
var certificate = new X509Certificate2(Convert.FromBase64String([**certificateBase64**]), [**certificatePassword**], X509KeyStorageFlags.MachineKeySet);
X509SecurityKey signingKey = new X509SecurityKey(certificate);

```

**Comment by iwaldman** [comment]
Hi @GeoK Okay, I will give that a try.

**Comment by iwaldman** [comment]
Hi @GeoK My KeyingMaterial class was lifted from yours. I just changed the byte strings. So my code is the same:

```
public static X509Certificate2 CertSelfSigned2048_SHA256 = new X509Certificate2(Convert.FromBase64String(SelfSigned2048_SHA256), "", X509KeyStorageFlags.PersistKeySet);
        public static X509SecurityKey X509SecurityKeySelfSigned2048_SHA256 = new X509SecurityKey(CertSelfSigned2048_SHA256);
        
```

**Comment by GeoK** [comment]
@iwaldman - I was not able to reproduce this issue.
I used the function below to troubleshoot. Notice that I added three lines of code under _test utility code_ comment.

```csharp
#r "Newtonsoft.Json"
#r "Microsoft.IdentityModel.Tokens"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography.X509Certificates;
using System.Security.Claims;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
    var result = CreateJWT5(log);

    return result != null
      ? (ActionResult)new OkObjectResult($"Access token: {result}")
      : new BadRequestObjectResult("Error - check logs.");
}

  static string CreateJWT5(ILogger log)
        {
            try
            {
                var audience = "https://login.cloud.com";
                var tenantId = "15dc65f8-f9ef-4133-af64-dce5bd1f1324";
                var issuer = "urn:pros:portal:acct:" + "c3124cd5-c250-480f-8ef1-70515dba9cd9";
                var scope = "urn:pros:portal:app:" + "d363cfa0-14b0-4224-a0f7-653f0fc29d63";

                var utc0 = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
                var issueTime = DateTime.UtcNow;

                var iat = (Int64)issueTime.Subtract(utc0).TotalSeconds;
                var exp = (Int64)issueTime.AddMinutes(55).Subtract(utc0).TotalSeconds;

                //test utility code
                string SelfSigned2048_SHA256 = @"MIIKYwIBAzCCCiMGCSqGSIb3DQEHAaCCChQEggoQMIIKDDCCBg0GCSqGSIb3DQEHAaCCBf4EggX6MIIF9jCCBfIGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhxE338m1L6/AICB9AEggTYMrXEnAoqfJTuvlpJieTu8LlJLL74PWG3GJmm+Rv45yMFjm332rVZKdLEOFmigUGGMfjk7uFBBLSpm3L/73g2LdNBFhMFnmdWlw0Nzs/Q4pxmHN+b9YPWv8KpiFc/CIUl30Nqf7NHk1CdM026iuY/eJlIO6eM8jWz/NP4pK+kZav5kvQIrZ6n1XYstw7Fw8Ils4pCGUsiFwNGFuSVLCRwxHqvEUgVmV3npUbCwKATSRNcs23LGHo4oZO1sj4u7cT66ke5Va/cGLrIPz4d+VelRkrPCcbgFi4bo24aA9b8dayMV7olDF+hbHTH9pYfPV5xUejsfGeX4BM7cH6Kp7jKKXJQq9MD26uEsrK9Bt4eoO1n4fK59+u0qSI7329ExsPA76uL9E5Xd+aDUpOUyJRCtnjY/Nz9IO/6zR5wdL72ux8dEzJAYqRgpmwIgyaXE7CYqmc9VHE65zddcpOFicVIafXfftAmWAPuyvVxkij04uAlSH2x0z+YbHG3gSl8KXpzfRmLeTgI1FxX6JyIV5OV8sxmvd99pjnosT7Y4mtNooDhx3wZVuPSPb7RjIqFuWibEyFLeWbCZ418GNuTS1CjpVG9M+i1n3P4WACchPkiSSYD5U9bi/UiFIM2yrAzPHpfuaXshhorbut3n/WBXLHbW/RAqOWMeAHHiJNtyq2okTM6pqp09HGjc3TbDVzyiA5EgfEdMPdXMNDZP7/uVFk+HQAm35Mrz+enMHjnLh4d8fy2yRuMs1CTLrQrS3Xh1ZbUn6EJ5EaZCMjoGd4siBIOuQvrxRwYfpnRB+OYMetkpUtMFCceMTS809zAS+rXxZ9Nfnk1q5c73+f0p9UZTLzajwNhPMhtQL1xYA2tVobVA+6hSxb7bgiH7+2qhoTBkmwzEkfXg7ALL2erBWHJJn5Hr8e4C3OdDFo/qCfA1E9IK3qIyLTzbhQnNRD+6KKTPP2ynGCJz2oIn6gmh29jKLwZc69FHMHdikevk58EXzKmHK9sy6YAFXQ4pBRKpaNwiQiNbUJsO/WYQ9CSoKRQjBOs7l1UbB2roYRXuUyZ+pLjOXnzaHOjF4nrNL8PP6XnCfJUXfmpQpaY/Q0zT4R1Zw+lXjfKoVd5JFPoWjoHGNQyFnvlyyUldB3jHQptbtUjV4fkeKXPhqcjn3QMSwN9nbwqiig88fiItVJFmDHemywfyiEtsDwc5yann0vNquegT/W9G0dq/7+z3e8V9e8040RpdepKiHH4o9cmyIT8gUNkXkJXsN9ZNaekUCGuhTqpzM2K3+zW1K7lTLq9/w3malhfIYw0mdHx2bz6nkyf6XezCQt7Fwc263r+YbAV16hjJJaTZcIqggoe5Al8B48mcCmGwNBF+Le/4/yoArzxlLbbljG3xIODJa+Vh01lWqK09mRbNpUjUtHswLuve48vabA2aZZmoxlsN3e7wLywrZ+Tvg4zg8R2ZzjjCXHkBI7qtZZZxMe+x2w3NbTnN54Gk1U/Pg3nVj242qCWR43A1Cp6QRrhi2fsVoNZCuHSUkykhH6q3Y/06OdgVyCyboXh0XnttlLbNLp3Wd8E0Hzr0WEm/Tdv1VDNu5R3S73VX1WIJ6z3jyTvm9JkzJFAxrk0mwAzBOSS34eYRQnhWFCT8tqHWIAzHyH+YJ9RmTGB4DANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBbBgkqhkiG9w0BCRQxTh5MAHsANwBBADIAMABDAEMAOQAzAC0AOABFAEEAMQAtADQAQQA2ADYALQA4AEEAMwA4AC0AQQA2ADAAQwAyADUANAA2ADEANwA3ADAAfTBdBgkrBgEEAYI3EQExUB5OAE0AaQBjAHIAbwBzAG8AZgB0ACAAUwB0AHIAbwBuAGcAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIID9wYJKoZIhvcNAQcGoIID6DCCA+QCAQAwggPdBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAhbuVGIv2XFPQICB9CAggOwUo/TgmdO5qDdDqOguXP1p5/tdAu8BlOnMbLQCB4NJ+VU3cnmzYAJ64TlkLqXGCww+z6aKVqtEODud5KMwVuUkX1Eu9Q+kLpMF1y6chkCVmfmMOzU0PsfMWghYSp4FEtWuYNzVQ869qrMCpVDoX8jUroUVkX3BV8sVUV7ufFYdFbwo++c/yCtrHxw4/oagjkXZXV9QBns+fLraJU/mO7isZJwHjscAZhckTdHGEr7hOqD/sHLPXYAgYCmkplH6aSNdyc6VmFXxmpKYFwlGnSA+xlJNcwrfyrljg5iUjpFMCcUuuOhjDCkIgTYsyT48uOgkoBLQzuQ8Oua3tpG1DQ6x2HJSHhQaILpNMZ6nWUrt9YRjdJHdCtdZGN/FPrASd8Vi68XIHu4dAy9zXKSL7GxsBCXXTE/XYca0v3rOnpvye1yt3zxssKPoMlgSUxsoUj9Moqyt+bjYJqV8tJwGt1xpB3k+QgpkmJnMY2i18r9sm59q2t+mWFfFwq/bIozNbzPBNzqq1q4fl80/7qEX046+KybgjaUrIAPiBYsTlAGNMfUAPuO/vb/FTq5Pk9SXepEqc+NkXrkOGzskOALefD9+DWDOy4j1loCvIXjLb1B9e4C5AIqzU4Sxq9YaDgVIVSK9GoVriaq8WQUSBktPruQD1rgPiHr94LZ0RgEBAReO9x3ljCXon6/sJEFUR024zbmEKol+HuY7HMPRzY5113nodOMYsYMFK5G+g4x5WtANN/qnoV16laBqJvQJ0iCj3LH8j0ljCPEMFUl87/Yp1I6SYrD9CycVNo3GuXdNFxKlKCUlf5CVjPWEhfM1vEvUSqwQuPEJ8gj9zK2pK9RpCV3E3Jo+47uNKYQQlh/fJd5ONAkpMchs303ojw7wppwQPqXavaHWX3emiZmR/fMHpVH812p8pZDdKTMmlk2gHjN7ysY3eBkWQTRTNgbrR2cJ+NIZjU85RA7/5Nu8630y1zBEe24RShio7yQjFawF1sdzySyWAl+qOMm7/x488qpfMQet7BzSuFPXqt3HCcH2vH2h2QFLgSA6/6Wx5XVeSQJ0R0rmS0cqAKlh9kqsX2EriG/dz2BxXv3XRymN2vMC9UOWWwwaxRh6DJv/UTHLL+4p6rLDC1GXZ/O4TVqKxNe9ShpzJx2JGwBl5VW4Rqo4UNTZTMn/L6xpfcdtVjpV+u5dD6QGBL57duQg9zqlJgMRbm/zjbC80fMjHpjbEUkf9qkl3mqEFp/vtrFiMCH4wH7bKswNzAfMAcGBSsOAwIaBBTjZISkPzPwKqSDK4fPHZMa83IUXgQUt9xlRgPPpTLoO5CUzqtQAjPN124=";
                X509Certificate2 CertSelfSigned2048_SHA256 = new X509Certificate2(Convert.FromBase64String(SelfSigned2048_SHA256), "SelfSigned2048_SHA256", X509KeyStorageFlags.MachineKeySet);
                X509SecurityKey X509SecurityKeySelfSigned2048_SHA256 = new X509SecurityKey(CertSelfSigned2048_SHA256);
          
                X509SecurityKey signingKey = X509SecurityKeySelfSigned2048_SHA256;
                var signingCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.RsaSha256Signature);

                var header = new JwtHeader(signingCredentials);
                header.Clear();
                header.Add("alg", "RS256");
                header.Add("typ", "JWT");

                var payload = new JwtPayload(
                    issuer,
                    audience,
                    new List<Claim>() {
                        new Claim("tid", tenantId),
                        new Claim("scope", scope),
                        new Claim(JwtRegisteredClaimNames.Iat, iat.ToString(), ClaimValueTypes.Integer64),
                        new Claim(JwtRegisteredClaimNames.Exp, exp.ToString(), ClaimValueTypes.Integer64)
                    },
                    null,
                    null
                );

                var jwtToken = new JwtSecurityToken(header, payload);
                var handler = new JwtSecurityTokenHandler();

                log.LogInformation("Calling WriteToken");

               // FAILS HERE
                var jwt = handler.WriteToken(jwtToken);

                log.LogInformation(String.Format("Access Token {0}", jwt));

                return jwt;
            }
            catch (Exception ex)
            {
                log.LogError("Exception {0} {1} {2} {3}", ex.HResult, ex.Message, ex.InnerException, ex.StackTrace);
            }
            return null;
        } 
```

**Comment by iwaldman** [comment]
@GeoK First, thank you. Let me take your code and try myself.  I may have missed something.

**Comment by iwaldman** [comment]
Hi @GeoK I tested using your code and it worked for me.  After more testing, the key was using X509KeyStorageFlags.MachineKeySet.  This is all new to me so I am not sure why this worked whereas using X509KeyStorageFlags.PersistKeySet did not.  Can you explain?  Anyway, thank you so much.

**Comment by GeoK** [comment]
Both flags are working fine for me, so I guess it's a permission/configuration issue on your side.
This code is a _test code_ and I would advise looking into [key vault](https://docs.microsoft.com/en-us/azure/key-vault/ ) for certificate/secrets management.
