### ISSUE TITLE
RSA-OAEP-256 not in SupportedAlgorithms.IsSupportedRsaAlgorithm()

### ISSUE THREAD

**Issue by Cristallix** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1293]
I'm trying to decrypt a JWE + JWS token and here is the first part of the token :

`eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0`

which after a base64ToString is giving : 

`{"zip":"DEF","enc":"A256CBC-HS512","alg":"RSA-OAEP-256"}`

The problem is that when I'm trying to decrypt the token it goes down to the method _SupportedAlgorithms.IsSupportedRsaAlgorithm()_ but RSA-OAEP-256 isn't listed and I can't decrypt my token. Do you plan to support it any time soon or I'm missing something ?

Thanks !

**Comment by GeoK** [comment]
Hi @Cristallix - RSA-OAEP-256 is not currently supported.
I don't see a reason why we shouldn't support it in net461 and netstandard targets.

The team will triage the issue soon, but for now I'm marking it as an _enhancement proposal_.

**Comment by shjin404** [comment]
Yes, we want to use this as well given SHA1 is now discouraged and people are recommended to use SHA2 family. 

@brentschmaltz Minor, but there is a bug in the exception message as well that it shows 'System.String' as Algorithm. It should say No support for Algorithm: 'RSA-OAEP-256', ...

```
Microsoft.IdentityModel.Tokens.SecurityTokenEncryptionFailedException
  HResult=0x80131500
  Message=IDX10615: Encryption failed. No support for: Algorithm: 'System.String', SecurityKey: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey'.
  Source=Microsoft.IdentityModel.JsonWebTokens
  StackTrace:
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.EncryptTokenPrivate(String innerJwt, EncryptingCredentials encryptingCredentials, String compressionAlgorithm, IDictionary`2 additionalHeaderClaims) in D:\a\1\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebTokenHandler.cs:line 856
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.CreateTokenPrivate(JObject payload, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, String compressionAlgorithm, IDictionary`2 additionalHeaderClaims) in D:\a\1\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebTokenHandler.cs:line 501
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.CreateToken(String payload, EncryptingCredentials encryptingCredentials) in D:\a\1\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebTokenHandler.cs:line 305
   at CredentialManagement.Program.DemoJwe() in C:\Users\...\source\repos\CredentialManagement\Program.cs:line 43
   at CredentialManagement.Program.Main(String[] args) in C:\Users\...\source\repos\CredentialManagement\Program.cs:line 22
```

**Comment by rudeGit** [comment]
@brentschmaltz Is this being addressed in the new release? What does v6 Next mean?

**Comment by killerjoe1990** [comment]
+1 running into exact same issue, need this added asap plz

**Comment by jlodom** [comment]
+1 This was one of two issues I ran into in the question below (I will be updating the entry in the next 24 hours to reflect solution/workaround hopefully). 
https://stackoverflow.com/questions/68106472/decrypting-jsonwebtoken-using-jsonwebkey-or-jsonwebkeyset-in-c-sharp
Since the alg does have cross-platform support in dotnet generally, it would be good to have:
https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography

**Comment by JonathanAtBitaddict** [comment]
+1 
This would really be needed

**Comment by lapo-luchini** [comment]
> (I will be updating the entry in the next 24 hours to reflect solution/workaround hopefully

I tried the work-around and it works for OAEP-256.

(AES-GCM _decryption_ works fine without any change, so in the end I decided it wasn't worth it to add support for AES-GCM encryption to the provider.)

```C#
using System.Security.Cryptography;
using Microsoft.IdentityModel.Tokens;

// inspired to: https://stackoverflow.com/a/68272468/166524
public class OAEP256CryptoProvider : ICryptoProvider
{
    public const string OAEP_256 = "RSA-OAEP-256";

    public bool IsSupportedAlgorithm(string algorithm, params object[] args)
    {
        return (algorithm == OAEP_256);
    }

    public object Create(string algorithm, params object[] args)
    {
        return new RsaOaepKeyWrapProvider(args[0] as SecurityKey, algorithm);
    }

    public void Release(object cryptoInstance)
    {
    }

    private class RsaOaepKeyWrapProvider : KeyWrapProvider
    {
        public RsaOaepKeyWrapProvider(SecurityKey key, string algorithm)
        {
            Key = (RsaSecurityKey) key;
            Algorithm = algorithm;
        }

        protected override void Dispose(bool disposing)
        {
        }

        public override byte[] UnwrapKey(byte[] keyBytes)
        {
            return Key.Rsa.Decrypt(keyBytes, RSAEncryptionPadding.OaepSHA256);
        }

        public override byte[] WrapKey(byte[] keyBytes)
        {
            return Key.Rsa.Encrypt(keyBytes, RSAEncryptionPadding.OaepSHA256);
        }

        public override string Algorithm { get; }
        public override string Context { get; set; }
        public override RsaSecurityKey Key { get; }
    }

}
```

**Comment by CurlyFire** [comment]
+1 I would also need this, thanks!

**Comment by Cristallix** [comment]
Support was merged since #2207, closing.

**Comment by karoberts** [comment]
As the author of that PR, I would like to point out that though it was merged in #2207, it was reverted 2 days later and remains not in place.  (see commit history above, [e9b0dda](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/e9b0ddac6878387d8b63a04d2bc3cd3bd0042abe) and [3f1697b](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/3f1697ba009f4f75f60ad1e1d2165361591857c3) I am not aware why.  I think this should be reopened.

**Comment by Cristallix** [comment]
Indeed. It would be cool to know why it was reverted and why it's still not implemented. Reopening.

**Comment by pmaytak** [comment]
From the past conversations I found that after we merged it, some tests failed; some [additional work is needed](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2636). We can put this back into the work queue.

>  [xUnit.net 00:00:29.71]     Microsoft.IdentityModel.Tokens.Tests.RsaKeyWrapProviderTests.RsaUnwrapMismatch(theoryData: AlgorithmMismatchRsaPKCS1RsaOAEP256, Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException, Substring: IDX10659:) [FAIL]
>   Failed Microsoft.IdentityModel.Tokens.Tests.RsaKeyWrapProviderTests.RsaUnwrapMismatch(theoryData: AlgorithmMismatchRsaPKCS1RsaOAEP256, Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException, Substring: IDX10659:) [3 ms]
>   Error Message:
>    Microsoft.IdentityModel.TestUtils.TestException : Microsoft.IdentityModel.Tokens.Tests.RsaKeyWrapProviderTests.RsaUnwrapParameterCheck : AlgorithmMismatchRsaPKCS1RsaOAEP256
>  
>  
> expectedException.TypeExpected != null: Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException
>  
>   Stack Trace:
>      at Microsoft.IdentityModel.TestUtils.TestUtilities.AssertFailIfErrors(String testId, List`1 errors) in D:\gh\azure-activedirectory-identitymodel-extensions-for-dotnet\test\Microsoft.IdentityModel.TestUtils\TestUtilities.cs:line 381
>    at Microsoft.IdentityModel.TestUtils.TestUtilities.AssertFailIfErrors(CompareContext context) in D:\gh\azure-activedirectory-identitymodel-extensions-for-dotnet\test\Microsoft.IdentityModel.TestUtils\TestUtilities.cs:line 362
>    at Microsoft.IdentityModel.Tokens.Tests.RsaKeyWrapProviderTests.RsaUnwrapMismatch(KeyWrapTheoryData theoryData) in D:\gh\azure-activedirectory-identitymodel-extensions-for-dotnet\test\Microsoft.IdentityModel.Tokens.Tests\RsaKeyWrapProviderTests.cs:line 188
>  
> Failed!  - Failed:     1, Passed:  1658, Skipped:     3, Total:  1662, Duration: 34 s - Microsoft.IdentityModel.Tokens.Tests.dll (net462)
