### ISSUE TITLE
Parse the jwt token information encrypted by HS512 algorithm

### ISSUE THREAD

**Issue by danvic712** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1412]
Hi
In my project, I need to verify a token generated by HS512 algorithm(generated by spring security), here is my code and the key is `mySecret`, and the program show this error
```csharp
var key = Encoding.UTF8.GetBytes(Configuration["Application:Jwt:SecurityKey"]);

services.AddAuthentication(configures =>
{
	configures.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
	configures.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
	configures.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
	options.TokenValidationParameters = new TokenValidationParameters
    {
        // ...
        IssuerSigningKey = new SymmetricSecurityKey(key),
        // ...
    };
    options.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            if (context.Exception.GetType() == typeof(SecurityTokenExpiredException))
            {
                context.Response.Headers.Add("Token-Expired", "true");
            }
            return Task.CompletedTask;
        }
    };
});
```
![image](https://user-images.githubusercontent.com/32116018/81774714-db0eec80-951d-11ea-8ceb-53faaa21dae1.png)

**Comment by brentschmaltz** [comment]
@Lanesra712 i am having a hard time following the exceptions as IDX10603 indicates we were unable to decrypt the JWE. While IDX10503 indicates a signature failure. But the JWE needs to be successfully before the signature can be verified.

Do you have an example JWE?

**Comment by danvic712** [comment]
@brentschmaltz 
hi, the sample jwt token is `eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJzeXNFbk5hbWVcIjpcIlRQTS1BUFAyLjBcIixcInVzZXJOYW1lXCI6XCIxMDAwXCJ9IiwiZXhwIjoxNTk1OTA4MTUwLCJpYXQiOjE1OTU5MDA5NTB9.TqBfAPwjP3yAgAT5L9S3WzGBu4naNdnc6Szbtu7iLh0jznG5LfjDCAtnE2OTjnzOGcKdonGnEWo-TJTr3QhInA` 
and the java source code is as follow 
```java
package com.xxxx.permission.security;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Clock;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.impl.DefaultClock;

@Component
public class JwtTokenUtil implements Serializable {

    private static final long serialVersionUID = -3301605591108950415L;
    private Clock clock = DefaultClock.INSTANCE;

    // the config value is mySecret
    @Value("${jwt.secret}")
    private String secret;

    // the config value is 720000
    @Value("${jwt.expiration}")
    private Long expiration;

    // the config value is Authorization
    @Value("${jwt.header}")
    private String tokenHeader;

    public String getUsernameFromToken(String token) {
        return getClaimFromToken(token, Claims::getSubject);
    }

    public Date getIssuedAtDateFromToken(String token) {
        return getClaimFromToken(token, Claims::getIssuedAt);
    }

    public Date getExpirationDateFromToken(String token) {
        return getClaimFromToken(token, Claims::getExpiration);
    }

    public <T> T getClaimFromToken(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = getAllClaimsFromToken(token);
        return claimsResolver.apply(claims);
    }

    private Claims getAllClaimsFromToken(String token) {
        return Jwts.parser()
            .setSigningKey(secret)
            .parseClaimsJws(token)
            .getBody();
    }
        
    private Boolean isTokenExpired(String token) {
        final Date expiration = getExpirationDateFromToken(token);
        return expiration.before(clock.now());
    }

    private Boolean isCreatedBeforeLastPasswordReset(Date created, Date lastPasswordReset) {
        return (lastPasswordReset != null && created.before(lastPasswordReset));
    }

    private Boolean ignoreTokenExpiration(String token) {
        return false;
    }

    public String generateToken(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        return doGenerateToken(claims, userDetails.getUsername());
    }

    private String doGenerateToken(Map<String, Object> claims, String subject) {
        final Date createdDate = clock.now();
        final Date expirationDate = calculateExpirationDate(createdDate);

        return Jwts.builder()
            .setClaims(claims)
            .setSubject(subject)
            .setIssuedAt(createdDate)
            .setExpiration(expirationDate)
            .signWith(SignatureAlgorithm.HS512, secret)
            .compact();
    }

    public Boolean canTokenBeRefreshed(String token, Date lastPasswordReset) {
        final Date created = getIssuedAtDateFromToken(token);
        return !isCreatedBeforeLastPasswordReset(created, lastPasswordReset)
                && (!isTokenExpired(token) || ignoreTokenExpiration(token));
    }

    public String refreshToken(String token) {
        final Date createdDate = clock.now();
        final Date expirationDate = calculateExpirationDate(createdDate);

        final Claims claims = getAllClaimsFromToken(token);
        claims.setIssuedAt(createdDate);
        claims.setExpiration(expirationDate);

        return Jwts.builder()
                .setClaims(claims)
                .signWith(SignatureAlgorithm.HS512, secret)
                .compact();
    }

    public Boolean validateToken(String token, UserDetails userDetails) {
        JwtUser user = (JwtUser) userDetails;
        final Date created = getIssuedAtDateFromToken(token);
        return (!isTokenExpired(token));
    }

    private Date calculateExpirationDate(Date createdDate) {
        return new Date(createdDate.getTime() + expiration);
    }
}
```

**Comment by brentschmaltz** [comment]
@Lanesra712 i was able to repro the same error stack as you have shown.
They way i achieved this is by using a 'key' that is too small. We don't accept keys smaller that 128 bits.
It looks like you are using 5.x version of IdentityModel that ships with asp.net by default.

We have improved the error message in 6.7.1. There is still an issue as we report the error as 'encryption'.
The next version of asp.net will use 6.7.1 as it's default.

**6.7.1 ErrorMessage**
```
Message: 
    exception: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: 'zoPQ7H_zemLYB6GqxnefRKF0wmtjIvdpmqB-t2-uQPg'. , KeyId: 
    '.
    Exceptions caught:
     'System.ArgumentOutOfRangeException: IDX10653: The encryption algorithm 'HS512' requires a key size of at least '128' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: 'zoPQ7H_zemLYB6GqxnefRKF0wmtjIvdpmqB-t2-uQPg'.', is of size: '64'.
    Parameter name: key
```
**5.x ErrorMessage**

```
      Message: 
        Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException : IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: '81a153bb-693d-498d-9de2-10ff7626b7fe'. , KeyId: 
        '.
        Exceptions caught:
         'System.ArgumentOutOfRangeException: IDX10603: Decryption failed. Keys tried: 'HS512'.
        Exceptions caught:
         '128'.
        token: '64'
        Parameter name: KeySize
           at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures) in E:\github\wilson\dev5x\src\Microsoft.IdentityModel.Tokens\SymmetricSignatureProvider.cs:line 82
           at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures) in E:\github\wilson\dev5x\src\Microsoft.IdentityModel.Tokens\CryptoProviderFactory.cs:line 454
           at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm) in E:\github\wilson\dev5x\src\Microsoft.IdentityModel.Tokens\CryptoProviderFactory.cs:line 249
           at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters) in E:\github\wilson\dev5x\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 825
           at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) in E:\github\wilson\dev5x\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 944
        '.
        token: '{"alg":"HS512"}.{"sub":"{\"sysEnName\":\"TPM-APP2.0\",\"userName\":\"1000\"}","exp":1595908150,"iat":1595900950}'.
```

**Comment by brentschmaltz** [comment]
I see that our 6.8.0 version throws the exception message that indicates the issue.
Please reopen if you have a concern.

IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: 'DefaultSymmetricSecurityKey_64', InternalId: '-qSp6nskC31aGkDN02flDnnvyTBsW1j60wpCIr8Qoc4'. , KeyId: DefaultSymmetricSecurityKey_64
'. 
kid: 'DefaultSymmetricSecurityKey_64'. 
Exceptions caught:
 'System.ArgumentOutOfRangeException: IDX10653: The encryption algorithm 'HS512' requires a key size of at least '128' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: 'DefaultSymmetricSecurityKey_64', InternalId: '-qSp6nskC31aGkDN02flDnnvyTBsW1j60wpCIr8Qoc4'.', is of size: '64'.
Parameter name: key
   at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures) in E:\github\wilson\brentsch\HS512Exception\src\Microsoft.IdentityModel.Tokens\SymmetricSignatureProvider.cs:line 80
