### ISSUE TITLE
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature throws unexpected ArgumentException

### ISSUE THREAD

**Issue by drago-draganov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1530]
Hello Team,

Recently started seeing unexpected ArgumentException exception during token validation. The documented contract doesn't suggest such behavior. A preceding call to JwtSecurityTokenHandler.CanReadToken returned true.

Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.2.2

Call stack:

System.ArgumentException: IDX12729: Unable to decode the header 'System' as Base64Url encoded string. jwtEncodedString: 'System.Security.SecureString'. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: K. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.DeserializeJwtHeader(String jsonString)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(String token)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)

**Comment by GeoK** [comment]
Hi @drago-draganov, it seems like you passed a secure string ('System.Security.SecureString') to JwtSecurityTokenHandler. The reason why CanReadToken returns **true** is because the method only counts dots and recognizes 'System.Security.SecureString' as a JWS (2 dots).
JwtSecurityTokenHandler doesn't support SecureStrings.

**Comment by drago-draganov** [comment]
Hi @GeoK, 
I don't think I follow. JwtSecurityTokenHandler.ValidateToken accept string as token value. I certainly don't explicitly pass SecureString. The JWT token is provided over the wire as a string. The first step is to validate it, therefore the call to JwtSecurityTokenHandler.ValidateToken.

**Comment by GeoK** [comment]
@drago-draganov Check if you can verify that you are not passing SecureString. Looking at the stack trace you posted, it looks like the string you passed is a SecureString. 
`Unable to decode the header 'System' as Base64Url encoded string. jwtEncodedString: 'System.Security.SecureString'. `

**Comment by drago-draganov** [comment]
@GeoK I'm not passing SecureString to JwtSecurityTokenHandler.ValidateToken for sure. How can one compile with SecureString argument, since the JwtSecurityTokenHandler.ValidateToken API signature accepts only String? Am I missing something?


The JWT token content itself is coming on the wire and I don't have control how and what is serialized. The error looks to me related to the deserialization of the token.

The error is recent and quite rare. It's certainly related to the JWT token value format. It works just fine for millions of other requests.

**Comment by GeoK** [comment]
Any chance that you can capture the token and reproduce? Looking at the stack trace, value of the token that you are passing to ValidateToken is 'System.Security.SecureString'.

**Comment by drago-draganov** [comment]
To clarify a bit. The issue is not that parsing the token fails due to bad payload, but the way it fails. The current ArgumentException is not expected. Perhaps should be manifested via SecurityTokenException?

**Comment by brentschmaltz** [comment]
@drago-draganov we can't change the exception as we could break users. 
We are moving towards JsonWebTokenHandler and I don't think this meets the bar.
