### ISSUE TITLE
It looks like the type name is in there where the actual date should be

### ISSUE THREAD

**Issue by c-yan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1541]
- The version you're using.

System.IdentityModel.Tokens.Jwt 6.8.0

- The behavior you're seeing. If at all possible, please submit a reduced repro or test that demonstrates the issue.

When the token expired, I got the following exception.

```
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
```

- What you expect to see.

I think the "ValidTo: 'System.DateTime', Current time: 'System.DateTime'." is supposed to contain the actual time (e.g. 2020-10-14T09:47:00Z).

**Comment by keegan-caruso** [comment]
This is the default censoring of any PII that is done by the library. We admit that it is not as obvious as it could be.

Please see this wiki item: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

Reopen if this doesn't answer your question.

**Comment by c-yan** [comment]
thanx!!

I have confirmed that the actual datetime will appear by `IdentityModelEventSource.ShowPII = true;`.

I understand that it is a specification, although it would be better to show `*protected*` instead of the type name, etc.
