### ISSUE TITLE
Bug in the logging of SecurityTokenExpiredException? 

### ISSUE THREAD

**Issue by JoeMarkov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1589]
In the logs (using Serilog), when I get an exception, I get this statement where the dates are the types instead of the actual values.

Bug or feature?

Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: **'System.DateTime'**, Current time: '**System.DateTime'**. 

A more complete stack trace:

```
[21:46:22 Information] Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

[21:46:22 Information] Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Bearer was not authenticated. Failure message: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.

[21:46:22 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /weatherforecast/auth responded 404 in 6997.9761 ms
```

**Comment by brentschmaltz** [comment]
@JoeMarkov this is a result of filtering of message parameters.
Have a look at: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII to understand how to turn this on.

**Comment by JoeMarkov** [comment]
Aha, thanks! I thought that when PII was activated that sensitive information would be replaced with ********* instead of the typename that is shown below. Displaying the typename just looks like a ToString() bug in the logging code like below:

The token is expired. ValidTo: '**System.DateTime**', Current time: **'System.DateTime**'.

**Comment by brentschmaltz** [comment]
@JoeMarkov we used to replace with ******, but we thought that showing the type might help in some cases.
