### ISSUE TITLE
Exception prints System.String instead of string contents

### ISSUE THREAD

**Issue by garrettleach** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1639]
I created a simple program to create a JWE but wanted to specify the encryption method and decided to wing the algorithm names before looking up the documentation. However the exception thrown does not mention the offending algorithm name, it instead mentions 'System.String'.

Version: 6.11.0 of System.IdentityModel.Tokens.Jwt

### What I see:
IDX10615: Encryption failed. No support for: Algorithm: 'System.String', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'.

### What I expect to see:
IDX10615: Encryption failed. No support for: Algorithm: 'someAlgorithmNameHere', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'.

---

Full exception I am seeing:
```
Microsoft.IdentityModel.Tokens.SecurityTokenEncryptionFailedException
  HResult=0x80131500
  Message=IDX10615: Encryption failed. No support for: Algorithm: 'System.String', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'.
  Source=Microsoft.IdentityModel.JsonWebTokens
  StackTrace:
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.GetSecurityKey(EncryptingCredentials encryptingCredentials, CryptoProviderFactory cryptoProviderFactory, Byte[]& wrappedKey)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.EncryptToken(JwtSecurityToken innerJwt, EncryptingCredentials encryptingCredentials, String tokenType)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(SecurityTokenDescriptor tokenDescriptor)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedJwt(SecurityTokenDescriptor tokenDescriptor)
   at Scratch5.Program.Main(String[] args) in [removedPath]\Program.cs:line 55
```

Reproduction code

```C#
        static void Main(string[] args)
        {
            var rsa = RSA.Create();
            var certRequest = new CertificateRequest("cn=Garrett", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

            using var cert = certRequest.CreateSelfSigned(DateTime.UtcNow, DateTime.UtcNow.AddMonths(1));

            var handler = new JwtSecurityTokenHandler();

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Audience = "you",
                Issuer = "me",
                Subject = new ClaimsIdentity(new List<Claim> { new Claim("sub", "garrett") }),
                EncryptingCredentials = new X509EncryptingCredentials(cert, "HMAC-SHA256", "AES -128-CBC") // These values are invalid and should cause an exception!
            };

            string token = handler.CreateEncodedJwt(tokenDescriptor); // Should throw IDX10615 but with algorithm name filled in
        }
```

**Comment by garrettleach** [comment]
This behavior _appears(?)_ to be intended to remove PII based on the call to RemovePII in Microsoft.IdentityModel.Logging.LogHelper.FormatInvariant.
