### ISSUE TITLE
Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime doesn't provide actual DateTimes

### ISSUE THREAD

**Issue by Pikhulya** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1762]
Microsoft.IdentityModel.Tokens 6.7.1.0

Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime throws an exception missing actual date times:

Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: **IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.**
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__3.MoveNext(). 

Searching issues here I see a [number of posts](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues?q=IDX10223%3A+Lifetime+validation+failed.+The+token+is+expired.+ValidTo%3A+%27System.DateTime%27%2C+Current+time%3A+%27System.DateTime%27.) where all of them are resolved sort of "by design" indicating that is done to not leak PII and then lead to the [page ](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) describing how to turn PII logging ON.

That explanation is very questionable because DateTime is not PII. Moreover, the only way to see datetimes would be to leverage

`IdentityModelEventSource.ShowPII = true;`

but it would mean that real PII, like security tokens failing validation containing user's details, would also be printed. So now we are stuck with not being able to see the Expiration related datetimes which are not PII and if we want to see them we would need to move our system at risk by setting the above property thus really logging PII.

Can you please fix this so System Information like DateTimes, are not considered as PII or at least whether they are logged or not is controlled by another switch - no the one which could result in real PII to be logged like ShowPII does?

**Comment by brentschmaltz** [comment]
@Pikhulya we are fixing this in the following PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1725

I would be great if you commented there.
