### ISSUE TITLE
[Bug] MissingMethodException is thrown (IDX20803)

### ISSUE THREAD

**Issue by tomaszzmudzinski** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1899]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel.Tokens 6.20.0

**Where is the issue?**
 * [x] M.IM.Logging
 * [x] M.IM.Tokens

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.Tokens (from 6.11.1 to 6.20.0)

**Repro**
Everything worked without any issues until I have upgraded Microsoft.IdentityModel.Tokens from 6.11.1 to 6.20.0. Now when I am trying to log in I am getting this exception:

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:5001/.well-known/openid-configuration'.
 ---> System.MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Logging.IdentityModelTelemetryUtil.SetTelemetryData(System.Net.Http.HttpRequestMessage)'.

**Expected behavior**
It should work as before without changing any settings or adding new NuGet Package. I tried to install Microsoft.IdentityModel.Logging package (before I had just Microsoft.IdentityModel.Tokens installed in my project) but it didn't helped. I can't find any breaking changes between versions 6.11.1 and 6.20.0 but maybe something has changed and needs to be changed?

**Actual behavior**
An exception in thrown, before upgrading to latest package version everything worked properly:

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:5001/.well-known/openid-configuration'.
 ---> System.MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Logging.IdentityModelTelemetryUtil.SetTelemetryData(System.Net.Http.HttpRequestMessage)'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by brentschmaltz** [comment]
@tomaszzmudzinski did you upgrade just M.IM.Tokens or all of the assemblies?
They must all be at the same version.

**Comment by tomaszzmudzinski** [comment]
> @tomaszzmudzinski did you upgrade just M.IM.Tokens or all of the assemblies? They must all be at the same version.

Only Microsoft.IdentityModel.Tokens package was installed in my solution (version 6.11.1). Everything worked perfectly and suddenly it started to throw given exception after upgrading this package to the latest version (6.20.0).

After it stopped working as expected I tried to add M.IM.Logging to my solution (also with version 6.20.0) but this didn't help.

Here is my current NuGet package explorer: (I'am working on VS for Mac / Jetbrains Rider)
<img width="899" alt="image" src="https://user-images.githubusercontent.com/4519335/176518882-8c41b895-ca7c-4e3a-a389-2422c2fa17c1.png">

**Comment by brentschmaltz** [comment]
@tomaszzmudzinski do you have any other packages installed, if so what are the versions.

**Comment by brentschmaltz** [comment]
@tomaszzmudzinski it appears that the version of M.IM.Protocols is still 6.11.1. Make sure all IdentityModel packages are the same version.

We changed the internal api post 6.11.1
6.11.1 we have: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/c408c65256d1171ec685485b0a52129abb5cf407/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L111

6.20.0 we have: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/053d0a4b721ccae97ad041c84af9316f00a53678/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L150

**Comment by tomaszzmudzinski** [comment]
> @tomaszzmudzinski it appears that the version of M.IM.Protocols is still 6.11.1. Make sure all IdentityModel packages are the same version.
> 
> We changed the internal api post 6.11.1 6.11.1 we have:
> 
> https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/c408c65256d1171ec685485b0a52129abb5cf407/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L111
> 
> 6.20.0 we have:
> 
> https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/053d0a4b721ccae97ad041c84af9316f00a53678/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L150

As I wrote before my solution had only one package installed: Microsoft.IdentityModel.Tokens so this is something else 😢

**Comment by slacksach** [comment]
We have the same issue, upgraded from 6.10.0, issue starts in 6.14 to 6.16

![image](https://user-images.githubusercontent.com/75119677/195881060-9f4489bb-09c1-432f-9e39-ced0d89d0980.png)
