### ISSUE TITLE
[Bug] When converting JWT tokens System.OverflowException is used internally for control flow

### ISSUE THREAD

**Issue by JeremyMahieu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1994]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
System.IdentityModel.Tokens.Jwt 6.12

**Where is the issue?**
 * [x] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
This is an existing app in production, the issue has always been there. But it's not critical, just log spam.

**Repro**
Log FirstChanceExceptions and do a request using a jwt token. When trying to read any jwt token that has dates, such as `exp` later than year 2038. (Unix time larger than Int32.MaxValue).

**Expected behavior**
Expecting no exceptions to be thrown internally, even exceptions that are caught by the program itself.

**Actual behavior**
Each time a request is done using a jwt token for authentication. If the jwt token has dates larger than Int32.MaxValue, an exception is thrown and caught internally in `GetIntClaim`. This causes log spam is the FirstChanceExceptions are logged.  This is an anti-pattern, decrease performance slightly.

The exception is thrown here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/82fda2c0ae2e6c623dcdb137b1ebcba918236d32/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L616

```
[2023-01-03 23:00:05Z DBG] FirstChanceException event raised in xxxxxxxxxxx
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
[2023-01-03 23:00:05Z DBG]    at xxxxxxxxx.<>c.<LogFirstChanceExceptions>b__2_0(Object source, FirstChanceExceptionEventArgs e)
   at System.Convert.ToInt32(Double value)
   at System.IdentityModel.Tokens.Jwt.JwtPayload.GetIntClaim(String claimType)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at EMX.Common.Middleware.WarnOldTokenMiddleWare.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at EMX.Common.Middleware.WarnOldTokenMiddleWare.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context, ICorsPolicyProvider corsPolicyProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
**Possible solution**
Use `Int64` conversion by default. Or do a check if the number is bigger than `Int32.MaxValue` instead of relying on the Exception for control flow of the program. I'm willing to attempt to create a PR if this issue is deemed valid.

**Additional context / logs / screenshots / links to code**
The JWT token looks something like this:
```json
{
  "sub": "xxx",
  "name": "xxx",
  "nbf": 1670852510,
  "exp": 4824452510,
  "iat": 1670852510,
  "iss": "xxx",
  "aud": "xxx"
}
```
In this case the "exp" field is bigger than 2147483647 and thus causes the exception.

**Comment by brentschmaltz** [comment]
@JeremyMahieu we are closing as we fixed this in our 7.x release. 
We are only fixing issues in 6.x associated with security.
