### ISSUE TITLE
[Bug] The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by henriqueholtztraycorp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2011]
Hi. I have an web app in .NET Framework 4.8. I have some 450 instances of this web app in several servers (Windows + IIS).

The error bellow occurs sporadically in some of those apps. I got the message from Event Viewer.

In all of these I have a LoadBalancer (ARR) who receive the request in HTTPS and send the request in HTTP to the application. 

The application back to the normal itself after some time (from seconds to minutes).

I'm considering upgrade some packages but I don't want to do it without making sure about the problem because I can't reproduce it manually and some times all the applications works well for weeks without any problem, and then the problem came back.

```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 01/02/2023 00:52:36 
Event time (UTC): 01/02/2023 03:52:36 
Event ID: f3b59082b37b406092eea1b5476a95ae 
Event sequence: 4 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /**/W3SVC/***/ROOT-1-1********** 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: E:\Plataforma_customapplicationname\Admin\ 
    Machine name: **IMP001 
 
Process information: 
    Process ID: 9880 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\customapplicationname - Admin 
 
Exception information: 
    Exception type: IOException 
    Exception message: IDX20804: Unable to retrieve document from: '[PII is hidden]'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()

An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()

The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

 
 
Request information: 
    Request URL: http://customapplicationname.customdomain.net:443/
    Request path: / 
    User host address: 10.0.0.** 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\customapplicationname - Admin 
 
Thread information: 
    Thread ID: 22 
    Thread account name: IIS APPPOOL\customapplicationname - Admin 
    Is impersonating: False 
    Stack trace:    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
```

My `packages.config`:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="ApacheThrift" version="0.9.3" targetFramework="net45" />
  <package id="AutoMapper" version="6.2.2" targetFramework="net45" />
  <package id="bootstrap" version="3.3.6" targetFramework="net45" />
  <package id="CsvHelper" version="2.16.3.0" targetFramework="net45" />
  <package id="Elmah.Mvc" version="2.1.2" targetFramework="net45" />
  <package id="Email.Framework" version="1.0.14" targetFramework="net461" />
  <package id="EntityFramework" version="6.4.4" targetFramework="net48" />
  <package id="EntityFramework.Extended" version="6.1.0.95" targetFramework="net4" requireReinstallation="true" />
  <package id="Facebook" version="6.8.0" targetFramework="net45" />
  <package id="FastMember" version="1.4.1" targetFramework="net461" />
  <package id="HtmlRenderer.Core" version="1.5.0.6" targetFramework="net45" />
  <package id="HtmlRenderer.PdfSharp" version="1.5.0.6" targetFramework="net45" />
  <package id="HtmlRenderer.WinForms" version="1.5.0.6" targetFramework="net45" />
  <package id="IdentityModel" version="1.12.0" targetFramework="net45" />
  <package id="iTextSharp" version="5.5.8" targetFramework="net45" />
  <package id="JavaScriptEngineSwitcher.ChakraCore" version="2.3.2" targetFramework="net45" />
  <package id="JavaScriptEngineSwitcher.Core" version="2.2.0" targetFramework="net45" />
  <package id="JavaScriptEngineSwitcher.Msie" version="2.3.2" targetFramework="net45" />
  <package id="JavaScriptEngineSwitcher.V8" version="2.2.0" targetFramework="net45" />
  <package id="jQuery" version="2.2.0" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.13.0" targetFramework="net4" />
  <package id="jQuery.Validation.Globalize" version="1.0.1" targetFramework="net45" />
  <package id="jQuery.Validation.Unobtrusive" version="2.0.20710.0" targetFramework="net45" />
  <package id="jQuery.vsdoc" version="1.6" targetFramework="net4" />
  <package id="jquery-globalize" version="0.1.3" targetFramework="net45" />
  <package id="JsonConfig" version="1.0.0" targetFramework="net45" />
  <package id="JsonFx" version="2.0.1209.2802" targetFramework="net45" />
  <package id="JSPool" version="2.0.1" targetFramework="net45" requireReinstallation="true" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc.pt-br" version="5.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.2" targetFramework="net461" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.3.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.2" targetFramework="net461" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.3.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.3.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net48" />
  <package id="Microsoft.jQuery.Unobtrusive.Ajax" version="3.2.0" targetFramework="net4" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.0" targetFramework="net45" />
  <package id="Microsoft.Owin" version="4.1.1" targetFramework="net48" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.1.1" targetFramework="net48" />
  <package id="Microsoft.Owin.Security" version="4.1.1" targetFramework="net48" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.1.1" targetFramework="net48" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.1.1" targetFramework="net48" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net4" />
  <package id="MicrosoftWebMvc" version="2.0" targetFramework="net4" />
  <package id="Modernizr" version="2.8.3" targetFramework="net45" />
  <package id="MsieJavaScriptEngine" version="2.1.2" targetFramework="net45" />
  <package id="Mvc2Futures" version="2.0.50217.0" targetFramework="net4" />
  <package id="MvcContrib" version="2.0.95.0" targetFramework="net4" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="PDFsharp" version="1.32.3057.0" targetFramework="net45" />
  <package id="React.Core" version="3.0.1" targetFramework="net45" />
  <package id="React.Web" version="3.0.1" targetFramework="net45" />
  <package id="React.Web.Mvc4" version="3.0.1" targetFramework="net45" />
  <package id="ServiceStack.Text" version="5.1.0" targetFramework="net461" />
  <package id="System.Dynamic.Runtime" version="4.0.0" targetFramework="net45" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net48" />
  <package id="System.Net.Http" version="2.0.20126.16343" targetFramework="net45" />
  <package id="System.Net.Http.Formatting.Extension" version="5.2.3" targetFramework="net45" />
  <package id="System.Web.Optimization.React" version="3.0.1" targetFramework="net45" />
  <package id="Thrift" version="0.9.1.3" targetFramework="net45" />
  <package id="VroomJs" version="1.2.3" targetFramework="net45" />
  <package id="WebActivatorEx" version="2.2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.6.0" targetFramework="net45" />
</packages>
```

Error:

![image](https://user-images.githubusercontent.com/81363452/216442506-f836c2e3-5d95-49c3-98ca-5b9b54ed0682.png)

**Comment by henriqueholtztraycorp** [comment]
Also any suggestions who can help me to reproduce manually would be helpfull.

**Comment by brentschmaltz** [comment]
@henriqueholtztraycorp this looks like the X509Certificate is not trusted tls.
This could be a TLS version or the certificate is expired or the subject name does not match the url.
