### ISSUE TITLE
GetConfigurationAsync issue

### ISSUE THREAD

**Issue by chungvodim** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2030]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 6.15.1.0

**Where is the issue?**
 * [ ] Microsoft.IdentityModel.Protocols.ConfigurationManager

**Is this a new or an existing app?**
The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue.

**Repro**
NA

**Expected behavior**
When the setting `AutomaticRefreshInterval` is reached, the configuration manager is able to handle a massive number of unauthorized requests without blocking queued requests.

**Actual behavior**
When the setting `AutomaticRefreshInterval` is reached, the configuration is blocking queued unauthorized requests.

**Possible solution**
Ref: https://github.com/dotnet/aspnetcore/issues/38467

- ```Right now it assumes the _refreshLock is acquired quickly and now still current. However, if the refresh takes too long and/or there's lock contention, then now could be outdated. `now should be updated inside the lock (line 136), and again after the refresh finishes (line 143)```

**Additional context / logs / screenshots / links to code**
```
at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
```
and
```
System.OperationCanceledException: The operation was canceled.
   at void System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async Task<bool> System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, int millisecondsTimeout, CancellationToken cancellationToken)
   at async Task<T> Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
   at async Task<AuthenticateResult> Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync() x 2
   at async Task<AuthenticateResult> Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.AuthenticateAsync()
   at async Task<AuthenticateResult> Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, string scheme)
   at async Task Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at async Task Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
```

**Comment by Tratcher** [comment]
There was some recent work to support a LastKnownGood configuration that might help with this situation:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1797/files

**Comment by patrick-blanc** [comment]
Hi, we are facing similar issue in our API.

Is there like any workaround for this ? We have this problem randomly when too many requests came to our API. 

```
System.OperationCanceledException:
   at System.Threading.CancellationToken.ThrowOperationCanceledException (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.SemaphoreSlim+<WaitUntilCountOrTimeoutAsync>d__31.MoveNext (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1+<GetConfigurationAsync>d__14.MoveNext (Microsoft.IdentityModel.Protocols, Version=6.23.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=5.0.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

This is occuring in our site that is basically the browser homepage for every employee in the company. Then the API is stuck and the only way to fix this is to restart the API.

**Comment by chungvodim** [comment]
> Hi, we are facing similar issue in our API.
> 
> Is there like any workaround for this ? We have this problem randomly when too many requests came to our API.
> 
> ```
> System.OperationCanceledException:
>    at System.Threading.CancellationToken.ThrowOperationCanceledException (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Threading.SemaphoreSlim+<WaitUntilCountOrTimeoutAsync>d__31.MoveNext (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1+<GetConfigurationAsync>d__14.MoveNext (Microsoft.IdentityModel.Protocols, Version=6.23.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=5.0.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
> ```
> 
> This is occuring in our site that is basically the browser homepage for every employee in the company. Then the API is stuck and the only way to fix this is to restart the API.

There are 2 options you can try to mitigate this issue:

1. Write your own `JwtSecurityTokenHandler`. Don't use built-in function `configurationManager.GetConfigurationAsync`
2. Set AutomaticRefreshInterval for at least 12 hours, and RefreshInterval for at least 5 minutes.

**Comment by suhspavn** [comment]
We are facing the same issue in .NET CORE 6.0 lib Microsoft.AspNetCore.Authentication.JwtBearer
The default AutomaticRefreshInterval is already set to 12 hours, and RefreshInterval we have 5 minutes, this did not help.

We were using our own token handler in .NET Framework we did not have this issue.

**Comment by chungvodim** [comment]
> We are facing the same issue in .NET CORE 6.0 lib Microsoft.AspNetCore.Authentication.JwtBearer The default AutomaticRefreshInterval is already set to 12 hours, and RefreshInterval we have 5 minutes, this did not help.
> 
> We were using our own token handler in .NET Framework we did not have this issue.

Can you show your code?

**Comment by suhspavn** [comment]
> > We are facing the same issue in .NET CORE 6.0 lib Microsoft.AspNetCore.Authentication.JwtBearer The default AutomaticRefreshInterval is already set to 12 hours, and RefreshInterval we have 5 minutes, this did not help.
> > We were using our own token handler in .NET Framework we did not have this issue.
> 
> Can you show your code?


<img width="704" alt="image" src="https://user-images.githubusercontent.com/47027999/224327222-6bc52039-355a-4d8c-8df2-d47e7e1cbc15.png">
