### ISSUE TITLE
[Bug] Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.

### ISSUE THREAD

**Issue by tomgordanms** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2039]
**Which version of Microsoft.IdentityModel are you using?**
 6.26.1 

I tried update my Nugets (IdentityModel from 6.25 to 6.26.1 , and S2S from 3.32.0 to 3.42.1).
I have tests in which I generate a token and add generated signing key to context, 
but after the Nugets upgrade all tests fails, not finding the signing key. 

```
MISE16004: Inbound policy validation failed. Policy label: 'b0dc6175-11b9-4f38-a43c-3b14bcde0f77', failure type: 'SignatureKeyNotFound', failure message: 'S2S12086: An exception has been caught while validating the request applying the policy with id : 'b0dc6175-11b9-4f38-a43c-3b14bcde0f77'. Exception: Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ThrowOnTokenValidationError(String token, Exception exception, Boolean isValid, S2SContext context, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateBearerAsync(S2SInboundPolicy policy, ProtocolEvaluationResult protocolEvaluationResult, TokenValidationParameters tokenValidationParameters, S2SContext context)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateInternalAsync(S2SInboundPolicy policy, ProtocolEvaluationResult protocolEvaluationResult, S2SContext context)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateProtocolEvaluationResultAsync(ProtocolEvaluationResult protocolEvaluationResult, S2SContext context)'. See https://aka.ms/sal/authentication-errors/policy. 

```

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [X] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**

**Repro**

this is How I generate token:
```csharp
        sd = new SecurityTokenDescriptor
        {
            Issuer = tokenFactoryParams.UsedIssuer,
            Audience = tokenFactoryParams.Audience,
            Claims = new Dictionary<string, object>
            {
                ["aud"] = tokenFactoryParams.Audience!,
                ["iss"] = tokenFactoryParams.UsedIssuer!,
                ["exp"] = ConvertDateTimeToExpirationClaim(tokenFactoryParams.TokenExpiry),
                ["appid"] = tokenFactoryParams.AppId!,
                ["family_name"] = "Doe",
                ["given_name"] = "John",
                ["ipaddr"] = "127.0.0.1",
                ["oid"] = TokenTestOid,
                ["scp"] = tokenFactoryParams.Scp,
                ["tid"] = tokenFactoryParams.TenantId!,
                ["unique_name"] = "testadmin@evostsoneboxtest.com",
                ["upn"] = "testadmin@evostsoneboxtest.com",
                ["uti"] = TokenTestUti,
                ["ver"] = "1.0",
            },
            Expires = tokenFactoryParams.TokenExpiry,
            SigningCredentials = new SigningCredentials(
                key: tokenFactoryParams.SigningKey,
                algorithm: SecurityAlgorithms.RsaSha256Signature,
                digest: SecurityAlgorithms.RsaSha256Signature)
        };
    }
string tokenStr = new JsonWebTokenHandler().CreateToken(securityDescriptor);
// This is how I set the key & Validation params 

       var inboundPolicy = new JwtInboundPolicy(Authority, clientId);
        inboundPolicy.TokenValidationParameters.ValidateIssuer = true;
        inboundPolicy.TokenValidationParameters.ValidAudiences = new[] { Audience };
        inboundPolicy.TokenValidationParameters.ValidateAudience = true;
        inboundPolicy.TokenValidationParameters.IssuerValidator = AadIssuerValidator.GetAadIssuerValidator(Authority).Validate;
        inboundPolicy.ApplyPolicyForAllTenants = false;
        inboundPolicy.ValidAccessTokenTypes.Add(TokenType.AccessToken);
         inboundPolicy.TokenValidationParameters.IssuerSigningKey = IssuerSigningKey;
```

**Expected behavior**
Token Validation Passes with no Exc
**Actual behavior**
```
MISE16004: Inbound policy validation failed. Policy label: 'b0dc6175-11b9-4f38-a43c-3b14bcde0f77', failure type: 'SignatureKeyNotFound', failure message: 'S2S12086: An exception has been caught while validating the request applying the policy with id : 'b0dc6175-11b9-4f38-a43c-3b14bcde0f77'. Exception: Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ThrowOnTokenValidationError(String token, Exception exception, Boolean isValid, S2SContext context, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateBearerAsync(S2SInboundPolicy policy, ProtocolEvaluationResult protocolEvaluationResult, TokenValidationParameters tokenValidationParameters, S2SContext context)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateInternalAsync(S2SInboundPolicy policy, ProtocolEvaluationResult protocolEvaluationResult, S2SContext context)
   at Microsoft.IdentityModel.S2S.JwtAuthenticationHandler.ValidateProtocolEvaluationResultAsync(ProtocolEvaluationResult protocolEvaluationResult, S2SContext context)'. See https://aka.ms/sal/authentication-errors/policy. 
```

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by victorolawale** [comment]
@tomgordanms I am also having same issue. How were you able to resolve this? Please help.

**Comment by tomgordanms** [comment]
@victorolawale make sure you have KeyId set on your signing key
```
var key = new RsaSecurityKey(rsaKey.Rsa.ExportParameters(true))
{
         KeyId = "TestKeyId";
}
```
