### ISSUE TITLE
[Bug] Unable to decrypt JWT that has been protected with A256GSM within Linux docker container

### ISSUE THREAD

**Issue by lowds** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2126]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 
Microsoft.IdentityModel 6.31

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is a customer-facing demonstration web app shipping to production trying to host within a Linux docker container migrating from a Windows Azure App Service

**Repro**

```csharp
var tokenHandler = new JwtSecurityTokenHandler();
var principal = tokenHandler.ValidateToken(jwt, new TokenValidationParameters
{
    TokenDecryptionKey = secretKey, // loaded from configuration
    IssuerSigningKeys = securityKeys, // loaded from an external web app (the issuer of the JWT)
    ValidateAudience = false, // just for convenience we are turning these off but in a production application they would all be true
    ValidateIssuer = false,
    ValidateLifetime = false,
}, out _);
```

**Expected behavior**
A JWT encrypted with A256GSM is successfully decrypted when running within a Linux docker container.

**Actual behavior**
Application throws an exception reporting missing DLL (see additional context)

**Possible solution**

**Additional context / logs / screenshots / links to code**
Sample header for an encrypted JWT:

```
{
  "cty": "JWT",
  "enc": "A256GCM",
  "alg": "dir"
}
```

This stack trace has been captured when running in a docker image from "mcr.microsoft.com/dotnet/aspnet:7.0", same result when using aspnet 6.0 image.

```
SecurityTokenDecryptionFailedException: IDX10603: Decryption failed. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: '1Z2qK6XMBoUzmgZTQvBEXVWxVYSy2UXwGtYVmt-tyz0'.
'.
Exceptions caught:
'System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Tokens.AesGcm' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'BCrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.8/BCrypt.dll.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net7.0/BCrypt.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.8/libBCrypt.dll.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net7.0/libBCrypt.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.8/BCrypt.dll: cannot open shared object file: No such file or directory
/app/bin/Debug/net7.0/BCrypt.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.8/libBCrypt.dll: cannot open shared object file: No such file or directory
/app/bin/Debug/net7.0/libBCrypt.dll: cannot open shared object file: No such file or directory

at Microsoft.IdentityModel.Tokens.Interop.BCrypt.BCryptOpenAlgorithmProvider(SafeAlgorithmHandle& phAlgorithm, String pszAlgId, String pszImplementation, Int32 dwFlags)
at Microsoft.IdentityModel.Tokens.Cng.BCryptOpenAlgorithmProvider(String pszAlgId, String pszImplementation, OpenAlgorithmProviderFlags dwFlags)
at Microsoft.IdentityModel.Tokens.AesBCryptModes.<>c__DisplayClass0_0.<OpenAesAlgorithm>b__0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at Microsoft.IdentityModel.Tokens.AesGcm..cctor()
--- End of inner exception stack trace ---
at Microsoft.IdentityModel.Tokens.AesGcm.ImportKey(Byte[] key)
at Microsoft.IdentityModel.Tokens.AesGcm..ctor(Byte[] key)
at Microsoft.IdentityModel.Tokens.AuthenticatedEncryptionProvider.CreateAesGcmInstance()
at Microsoft.IdentityModel.Tokens.DisposableObjectPool`1.CreateInstance()
at Microsoft.IdentityModel.Tokens.DisposableObjectPool`1.Allocate()
at Microsoft.IdentityModel.Tokens.AuthenticatedEncryptionProvider.DecryptWithAesGcm(Byte[] ciphertext, Byte[] authenticatedData, Byte[] iv, Byte[] authenticationTag)
at Microsoft.IdentityModel.Tokens.AuthenticatedEncryptionProvider.Decrypt(Byte[] ciphertext, Byte[] authenticatedData, Byte[] iv, Byte[] authenticationTag)
at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.DecryptToken(CryptoProviderFactory cryptoProviderFactory, SecurityKey key, String encAlg, Byte[] ciphertext, Byte[] headerAscii, Byte[] initializationVector, Byte[] authenticationTag)
at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.DecryptJwtToken(SecurityToken securityToken, TokenValidationParameters validationParameters, JwtTokenDecryptionParameters decryptionParameters)
```

If I create an endpoint within the code that returns whether AesGSM is supported then on both Windows and Linux platforms this returns true:

```
app.MapGet("/supported", context =>
{
    context.Response.StatusCode = 200;
    // will write true whether on Windows or Linux
    context.Response.WriteAsync("is supported = " + AesGcm.IsSupported);
    return Task.CompletedTask;
});
```

The issue is with the actual decryption within https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev/src/Microsoft.IdentityModel.Tokens/opensource/AesGcm , I assume maybe that the DllImports etc are Windows-specific?

Note that in older implementations of Microsoft.IdentityModel this would throw a PlatformNotSupportedException, but found this related issue that was for enabling it on Linux https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1882

**Comment by Adash-nitro** [comment]
2 years later still a thing, aspnet:8.0
A workaround is to do as in https://github.com/dotnet/aspnetcore/issues/60367#issuecomment-2660930366 (but with Aes256Gcm) 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2624
