### ISSUE TITLE
[Bug] Could not load type 'Microsoft.IdentityModel.Json.JsonConvert'

### ISSUE THREAD

**Issue by scoleman81** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2320]
**Which version of Microsoft.IdentityModel are you using?**
I am using 7.0.0 and the exception occurs.  If I downgrade to 6.32.3 the type exception goes away.

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [X] S.IM.Tokens.Jwt

**Is this a new or an existing app?**
This is an existing app that was running a very old version of Identity Model.  Found the issue as I was trying to upgrade to the latest version.

**Repro**
I have an app I use OpenIDConnect.  I am using version 7.0.5 of Microsoft.AspNetCore.Authentication.OpenIdConnect that depends on M.IM.Tokens version 7.0.0.  I have a need to use S.IM.Tokens.Jwt and when I use version 7.0.0 I get a Type Exception.  If I downgrade S.IM.Tokens.Jwt to 6.32.3 The error goes away, and functions as expected.  Exception:

System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)

**Expected behavior**
I would expect both packages to work correctly side by side on version 7.0.0

**Actual behavior**
System.TypeLoadException

**Possible solution**
I wonder if it is related to moving to System.Text.Json.  There was talk in the Notes that that was a major change in 7.0.

**Comment by jmprieur** [comment]
@scoleman81 : did you make sure that all the IdentityModel libraries have the same version 7.0.0 in your project and its recursive dependencies?

```shell
dotnet restore yourProject.csproj
dotnet list yourProject.csproj package  --include-transitive
```

to see the list of all packages dependencies.

**Comment by scoleman81** [comment]
Ugh, I think that is it.  There was a transitive package I missed.  I thought everything had been upgraded but I guess not.  Thanks for pointing me in the right direction.
