### ISSUE TITLE
[Bug] Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens

### ISSUE THREAD

**Issue by raymens** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2333]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel.Tokens 7.0.1

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
Existing app that we updated from 6.x to 7.x

**Repro**

```csharp
    public static AuthenticationBuilder AddIdentityAuthority(this AuthenticationBuilder builder, IdentityAuthorityScheme identityAuthority)
    {
        return builder.AddJwtBearer(identityAuthority.Scheme, options =>
        {
            options.Authority = identityAuthority.Url;
            options.RequireHttpsMetadata = true;

            options.AutomaticRefreshInterval = TimeSpan.FromHours(12);

            options.Audience = "someaud";

            options.TokenValidationParameters.NameClaimType = "name";
            options.TokenValidationParameters.RoleClaimType = "role";
        });
    }
}
```

**Expected behavior**
Loading the settings from our Duende.IdentityServer instance like before.

**Actual behavior**
An exception that completely breaks authentication.

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://{url}/.well-known/openid-configuration'.
 ---> System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Possible solution**
Downgrade to 6.x

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by jennyf19** [comment]
@raymens did you make sure that all the IdentityModel libraries have the same version 7.0.0 in your project and its recursive dependencies?

```shell
dotnet restore yourProject.csproj
dotnet list yourProject.csproj package  --include-transitive
```

to see the list of all packages dependencies. closing, please re-open if needed.

**Comment by eluchsinger** [comment]
The only explicit dependency I had was `System.IdentityModel.Tokens.Jwt`. I had to add `Microsoft.IdentityModel.Validators` manually and upgrade to `7.0.2`. I believe this is a bug in the `System.IdentityModel.Tokens.Jwt`, because it should require the correct versions.

**Comment by JordiPerello** [comment]
Same problem for me and same temporally solution adding Microsoft.IdentityModel.Validators to 7.0.2, thanks @eluchsinger 

@jennyf19 I will wait for a more appropriate solution

**Comment by ddfreiling** [comment]
Can confirm this is NOT fixed, and is exactly because we only had a dependency on `System.IdentityModel.Tokens.Jwt` as @eluchsinger noted. @jennyf19 I don't think this should have been closed.

We added `Microsoft.IdentityModel.Protocols.OpenIdConnect` as a dependency, since that's the protocol we were actually using, and it worked as expected after that.

**Comment by jmprieur** [comment]
@ddfreiling 
What did you see (before your changes) where you were running:

```text
dotnet restore yourProject.csproj
dotnet list yourProject.csproj package  --include-transitive
```

**Comment by ddfreiling** [comment]
@jmprieur this is the before & after adding `Microsoft.IdentityModel.Protocols.OpenIdConnect 7.0.1` as an explicit dependency.

Before:
```
❯ dotnet list Merkur/Merkur.csproj package  --include-transitive | grep IdentityModel
   > Microsoft.IdentityModel.Abstractions                                               7.0.1   
   > Microsoft.IdentityModel.JsonWebTokens                                              7.0.1   
   > Microsoft.IdentityModel.Logging                                                    7.0.1   
   > Microsoft.IdentityModel.Protocols                                                  6.24.0  
   > Microsoft.IdentityModel.Protocols.OpenIdConnect                                    6.24.0  
   > Microsoft.IdentityModel.Tokens                                                     7.0.1   
   > System.IdentityModel.Tokens.Jwt                                                    7.0.1 
```
After:
```
❯ dotnet list Merkur/Merkur.csproj package  --include-transitive | grep IdentityModel
   > Microsoft.IdentityModel.Abstractions                                               7.0.1   
   > Microsoft.IdentityModel.JsonWebTokens                                              7.0.1   
   > Microsoft.IdentityModel.Logging                                                    7.0.1   
   > Microsoft.IdentityModel.Protocols                                                  7.0.1   
   > Microsoft.IdentityModel.Protocols.OpenIdConnect                                    7.0.1   
   > Microsoft.IdentityModel.Tokens                                                     7.0.1   
   > Microsoft.IdentityModel.Validators                                                 7.0.1   
   > System.IdentityModel.Tokens.Jwt                                                    7.0.1 
```

And it was giving this error when starting up pointed at our OpenID Connect authentication server, which seems to be one of the packages stuck at 6.x
`System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://{url}/.well-known/openid-configuration'.`
