### ISSUE TITLE
[Bug] Simple unit test fails with  "Could not load file or assembly, The located assembly's manifest definition does not match the assembly reference" after upgrade to 7.0.0

### ISSUE THREAD

**Issue by lennartb-** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2349]
**Which version of Microsoft.IdentityModel are you using?**
System.IdentityModel.Tokens.Jwt 7.0.2

**Where is the issue?**
 * [x] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [x] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment, but we experienced it also in production

**Repro**

https://github.com/lennartb-/JwtTestIssue

```csharp
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Contoso.Tests
{
    [TestClass]
    public class Tests
    {
        [TestMethod]
        public void JwtTest()
        {
            var jwtTokenHandler = new JwtSecurityTokenHandler();
            var descriptor = new SecurityTokenDescriptor();

            var token = jwtTokenHandler.CreateToken(descriptor);

            jwtTokenHandler.WriteToken(token);
        }
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.2" />
  </ItemGroup>

</Project>
```

**Expected behavior**
The unit test finishes without exception

**Actual behavior**
```
Test method Contoso.Tests.Tests.JwtTest threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at Contoso.Tests.Tests.JwtTest() in C:\Users\username\UnitTest1.cs:line 16
```

The assembly mentioned varies, on some computers we get the same message with `System.Text.Encodings.Web` or `System.Text.Json`.

**Possible solution**
The issue doesn't occur in System.IdentityModel.Tokens.Jwt versions < 7.0.0

**Additional context / logs / screenshots / links to code**
After upgrading to System.IdentityModel.Tokens.Jwt 7.0.0 we observed a failing unit test in our production system. We managed to reduce the issue to the minimal sample above.

**Comment by jennyf19** [comment]
Are all your M.IM versions the same? https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

**Comment by jmprieur** [comment]
See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/IdentityModel-7x#reminder

**Comment by jmprieur** [comment]
What is the result of the command:

```
dotnet restore yourProject.csproj
dotnet list yourProject.csproj package  --include-transitive
```
?

**Comment by lennartb-** [comment]
For the small demo project from above:
```
Project 'Contoso.Tests' has the following package references
   [net472]:
   Top-level Package                      Requested   Resolved
   > MSTest.TestAdapter                   3.1.1       3.1.1
   > MSTest.TestFramework                 3.1.1       3.1.1
   > System.IdentityModel.Tokens.Jwt      7.0.2       7.0.2

   Transitive Package                            Resolved
   > Microsoft.Bcl.AsyncInterfaces               1.1.0
   > Microsoft.IdentityModel.Abstractions        7.0.2
   > Microsoft.IdentityModel.JsonWebTokens       7.0.2
   > Microsoft.IdentityModel.Logging             7.0.2
   > Microsoft.IdentityModel.Tokens              7.0.2
   > System.Buffers                              4.5.1
   > System.Memory                               4.5.5
   > System.Numerics.Vectors                     4.5.0
   > System.Runtime.CompilerServices.Unsafe      4.7.1
   > System.Text.Encodings.Web                   4.7.2
   > System.Text.Json                            4.7.2
   > System.Threading.Tasks.Extensions           4.5.4
   > System.ValueTuple                           4.5.0
```

For our actual project with S.I.Tokens.JWT at 7.0.2:

```
Project 'ourproject.Tests' has the following package references
   [net472]:
   Top-level Package           Requested   Resolved
   > MSTest.TestAdapter        3.1.1       3.1.1
   > MSTest.TestFramework      3.1.1       3.1.1

   Transitive Package                                       Resolved
   > Antlr                                                  3.5.0.2
   > Azure.Core                                             1.25.0
   > Azure.Identity                                         1.7.0
   > EntityFramework                                        6.4.4
   > Flurl                                                  3.0.7
   > Flurl.Http                                             3.2.4
   > JetBrains.Annotations                                  2023.2.0
   > LumiSoft.Net.dll                                       4.7.8187.33884
   > Microsoft.Bcl.AsyncInterfaces                          7.0.0
   > Microsoft.Bcl.HashCode                                 1.1.1
   > Microsoft.Data.SqlClient                               5.1.1
   > Microsoft.Data.SqlClient.SNI                           5.1.0
   > Microsoft.Extensions.Logging.Abstractions              6.0.0
   > Microsoft.Identity.Client                              4.47.2
   > Microsoft.Identity.Client.Extensions.Msal              2.19.3
   > Microsoft.IdentityModel.Abstractions                   7.0.2
   > Microsoft.IdentityModel.JsonWebTokens                  7.0.2
   > Microsoft.IdentityModel.Logging                        7.0.2
   > Microsoft.IdentityModel.Protocols                      6.24.0
   > Microsoft.IdentityModel.Protocols.OpenIdConnect        6.24.0
   > Microsoft.IdentityModel.Tokens                         7.0.2
   > MySqlConnector                                         2.2.7
   > Newtonsoft.Json                                        13.0.3
   > Npgsql                                                 7.0.6
   > Oracle.ManagedDataAccess                               21.11.0
   > PDFClown                                               0.1.2
   > Stub.System.Data.SQLite.Core.NetFramework              1.0.118
   > System.Buffers                                         4.5.1
   > System.Collections.Immutable                           7.0.0
   > System.Configuration.ConfigurationManager              6.0.1
   > System.Data.SQLite                                     1.0.118
   > System.Data.SQLite.Core                                1.0.118
   > System.Data.SQLite.EF6                                 1.0.118
   > System.Data.SQLite.Linq                                1.0.118
   > System.Diagnostics.DiagnosticSource                    6.0.0
   > System.IdentityModel.Tokens.Jwt                        7.0.2
   > System.IO                                              4.3.0
   > System.Memory                                          4.5.5
   > System.Memory.Data                                     1.0.2
   > System.Net.Http                                        4.3.4
   > System.Numerics.Vectors                                4.5.0
   > System.Runtime                                         4.3.0
   > System.Runtime.CompilerServices.Unsafe                 6.0.0
   > System.Runtime.InteropServices.RuntimeInformation      4.3.0
   > System.Security.AccessControl                          6.0.0
   > System.Security.Cryptography.Algorithms                4.3.0
   > System.Security.Cryptography.Encoding                  4.3.0
   > System.Security.Cryptography.Primitives                4.3.0
   > System.Security.Cryptography.ProtectedData             4.7.0
   > System.Security.Cryptography.X509Certificates          4.3.0
   > System.Security.Permissions                            6.0.0
   > System.Security.Principal.Windows                      5.0.0
   > System.Text.Encoding                                   4.3.0
   > System.Text.Encodings.Web                              7.0.0
   > System.Text.Json                                       7.0.0
   > System.Threading.Channels                              7.0.0
   > System.Threading.Tasks.Extensions                      4.5.4
   > System.ValueTuple                                      4.5.0
   > ZXing.Net                                              0.16.9
```

It seems the 6.x versions here of IM.Protocols come as a transitive dependency of Microsoft.Data.SqlClient, which we already have installed as the latest version. However, this doesn't explain why the minimal example also fails.

**Comment by brentschmaltz** [comment]
@lennartb- anything to report?

**Comment by lennartb-** [comment]
@brentschmaltz 
I've tried with the latest 7.3.1 and the issue persists:
```
Test method Contoso.Tests.Tests.JwtTest threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at Contoso.Tests.Tests.JwtTest() in C:\Users\xxxx
```

Package list:
```
dotnet list .\Contoso.Tests.csproj package --include-transitive
Project 'Contoso.Tests' has the following package references
   [net472]:
   Top-level Package                      Requested   Resolved
   > MSTest.TestAdapter                   3.2.1       3.2.1
   > MSTest.TestFramework                 3.2.1       3.2.1
   > System.IdentityModel.Tokens.Jwt      7.3.1       7.3.1

   Transitive Package                                         Resolved
   > Microsoft.ApplicationInsights                            2.21.0
   > Microsoft.Bcl.AsyncInterfaces                            1.1.0
   > Microsoft.IdentityModel.Abstractions                     7.3.1
   > Microsoft.IdentityModel.JsonWebTokens                    7.3.1
   > Microsoft.IdentityModel.Logging                          7.3.1
   > Microsoft.IdentityModel.Tokens                           7.3.1
   > Microsoft.Testing.Extensions.Telemetry                   1.0.1
   > Microsoft.Testing.Extensions.TrxReport.Abstractions      1.0.1
   > Microsoft.Testing.Extensions.VSTestBridge                1.0.1
   > Microsoft.Testing.Platform                               1.0.1
   > Microsoft.Testing.Platform.MSBuild                       1.0.1
   > Microsoft.TestPlatform.ObjectModel                       17.5.0
   > NuGet.Frameworks                                         5.11.0
   > System.Buffers                                           4.5.1
   > System.Collections.Immutable                             1.5.0
   > System.Diagnostics.DiagnosticSource                      5.0.0
   > System.Memory                                            4.5.5
   > System.Numerics.Vectors                                  4.5.0
   > System.Reflection.Metadata                               1.6.0
   > System.Runtime.CompilerServices.Unsafe                   5.0.0
   > System.Text.Encodings.Web                                4.7.2
   > System.Text.Json                                         4.7.2
   > System.Threading.Tasks.Extensions                        4.5.4
   > System.ValueTuple                                        4.5.0
```

**Comment by brentschmaltz** [comment]
@lennartb- i will look into it then, will be out for a couple of days, so sometime next week.

**Comment by lennartb-** [comment]
@brentschmaltz Have you had a chance to look into it yet?

**Comment by lennartb-** [comment]
Still failing with 7.6.0:

```
Test method Contoso.Tests.Tests.JwtTest threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at Contoso.Tests.Tests.JwtTest() in C:\Users\xxx\UnitTest1.cs:line 16
```

```
dotnet list .\Contoso.Tests.csproj package --include-transitive
Project 'Contoso.Tests' has the following package references
   [net472]:
   Top-level Package                      Requested   Resolved
   > MSTest.TestAdapter                   3.4.3       3.4.3
   > MSTest.TestFramework                 3.4.3       3.4.3
   > System.IdentityModel.Tokens.Jwt      7.6.0       7.6.0

   Transitive Package                                         Resolved
   > Microsoft.ApplicationInsights                            2.22.0
   > Microsoft.Bcl.AsyncInterfaces                            1.1.0
   > Microsoft.IdentityModel.Abstractions                     7.6.0
   > Microsoft.IdentityModel.JsonWebTokens                    7.6.0
   > Microsoft.IdentityModel.Logging                          7.6.0
   > Microsoft.IdentityModel.Tokens                           7.6.0
   > Microsoft.Testing.Extensions.Telemetry                   1.2.1
   > Microsoft.Testing.Extensions.TrxReport.Abstractions      1.2.1
   > Microsoft.Testing.Extensions.VSTestBridge                1.2.1
   > Microsoft.Testing.Platform                               1.2.1
   > Microsoft.Testing.Platform.MSBuild                       1.2.1
   > Microsoft.TestPlatform.ObjectModel                       17.5.0
   > NuGet.Frameworks                                         5.11.0
   > System.Buffers                                           4.5.1
   > System.Collections.Immutable                             1.5.0
   > System.Diagnostics.DiagnosticSource                      5.0.0
   > System.Memory                                            4.5.5
   > System.Numerics.Vectors                                  4.5.0
   > System.Reflection.Metadata                               1.6.0
   > System.Runtime.CompilerServices.Unsafe                   5.0.0
   > System.Text.Encodings.Web                                4.7.2
   > System.Text.Json                                         4.7.2
   > System.Threading.Tasks.Extensions                        4.5.4
   > System.ValueTuple                                        4.5.0
```

**Comment by lennartb-** [comment]
We've now switched to `Microsoft.IdentityModel.JsonWebToken` (for other reasons) and the issue also exists there. I've updated the repro repo in the original post with both versions.

_However_, enabling Auto-BindingRedirects resolves the issue for both libraries. I.e. adding the following to the csproj:

```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
