### ISSUE TITLE
[Bug] OpenIdConnectConfiguration Cannot Be Serialized

### ISSUE THREAD

**Issue by mgw854** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2383]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

Microsoft.IdentityModel.Protocols.OpenIdConnect 7.0.3

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [x] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
Existing application, upgrading from 6.x

**Repro**

```csharp
using (BufferedStream writer = new BufferedStream(context.Response.Body))
{
  using (Utf8JsonWriter jsonWriter = new Utf8JsonWriter(writer))
  {
    JsonSerializer.Serialize(jsonWriter, new OpenIdConnectConfiguration()
    {
      IntrospectionEndpoint = TestAuthenticationDefaults.AuthorityUrl,
      JwksUri = TestAuthenticationDefaults.AuthorityUrl + "/op/certs",
      TokenEndpoint = TestAuthenticationDefaults.AuthorityUrl + "/op/token"
    });
  }
}
```

**Expected behavior**
The OpenIdConnectConfiguration is serialized to the response

**Actual behavior**
An InvalidOperationException is thrown:

The ignore condition 'JsonIgnoreCondition.WhenWritingNull' is not valid on value-type member 'ClaimsParameterSupported' on type 'Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration'. Consider using 'JsonIgnoreCondition.WhenWritingDefault'.

**Possible solution**
Properly annotate all the properties on OpenIdConnectConfiguration

**Additional context / logs / screenshots / links to code**
```
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_IgnoreConditionOnValueTypeInvalid(String clrPropertyName, Type propertyDeclaringType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ConfigureIgnoreCondition(Nullable`1 ignoreCondition) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfoOfT.cs:line 448
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.set_IgnoreCondition(Nullable`1 value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 147
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.InitializeUsingMemberReflection(MemberInfo memberInfo, JsonConverter customConverter, Nullable`1 ignoreCondition, Boolean shouldCheckForRequiredKeyword) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 598
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.CreateProperty(Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/ReflectionJsonTypeInfoOfT.cs:line 201
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.LateAddProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/ReflectionJsonTypeInfoOfT.cs:line 86
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 907
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 570
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 536
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 546
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 65
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 103
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 32
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 40
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Utf8JsonWriter.cs:line 39

```

**Comment by brentschmaltz** [comment]
@joegoldman2 we will look into this.
