### ISSUE TITLE
[Bug] OpenIdConnectConfiguration serialization issue

### ISSUE THREAD

**Issue by yurii-babenko96-ideals** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2419]
**Which version of Microsoft.IdentityModel are you using?**
I'm trying to use Microsoft.IdentityModel.Protocols.OpenIdConnect version 7.0.3.

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [x] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.OpenIdConnect. The version 6.21.0 works fine.

**Repro**
Reproduces every time I try to JSON serialize `Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration` object.

```csharp
System.Text.Json.JsonSerializer.Serialize(new Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration());
```

this code produces the same result
```csharp
JsonSerializer.Serialize(new OpenIdConnectConfiguration(), new JsonSerializerOptions()
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        });
```

**Expected behavior**
I expect JSON serialization to happen without any issues.

**Actual behavior**
System.InvalidOperationException has been thrown.

**Possible solution**
Change `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]` to `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]` for ClaimsParameterSupported and any other value-type properties. or drop `[JsonIgnore]` for them at all, whatever fits you best :)

**Additional context / logs / screenshots / links to code**
Exception message and callstack:
System.InvalidOperationException
The ignore condition 'JsonIgnoreCondition.WhenWritingNull' is not valid on value-type member 'ClaimsParameterSupported' on type 'Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration'. Consider using 'JsonIgnoreCondition.WhenWritingDefault'.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_IgnoreConditionOnValueTypeInvalid(String clrPropertyName, Type propertyDeclaringType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ConfigureIgnoreCondition(Nullable`1 ignoreCondition)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulatePropertyInfo(JsonPropertyInfo jsonPropertyInfo, MemberInfo memberInfo, JsonConverter customConverter, Nullable`1 ignoreCondition, Boolean shouldCheckForRequiredKeyword, Boolean hasJsonIncludeAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreatePropertyInfo(JsonTypeInfo typeInfo, Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword, Boolean hasJsonIncludeAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean constructorHasSetsRequiredMembersAttribute, PropertyHierarchyResolutionState& state)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at MyVeryAwersomeCode.cs:line 42

**Comment by yurii-babenko96-ideals** [comment]
i see fix has been commited to dev branch at this revision: f6a6504ed7a68158253ba0d4221f8f985235c5bd

can you tell me when it's going to be released, please?

**Comment by brentschmaltz** [comment]
@yurii-babenko96-ideals  Early January.

**Comment by yurii-babenko96-ideals** [comment]
@brentschmaltz oh, guys, you are killing me :(((( i guess, you don't like hotfixes, do you? :)

okay, i guess i can only wait for a release, at least now i know how much, thank you. i'm closing this ticket as duplicate, because the root cause is already fixed.

have a nice day!
