### ISSUE TITLE
[Bug] Base64UrlEncoder.DecodeBytes returns empty array on invalid input; used to throw

### ISSUE THREAD

**Issue by chwarr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2485]
**Which version of Microsoft.IdentityModel are you using?**

Works: 6.35.0
First impacted version: 7.0.0
Latest impacted version: 7.3.1

**Where is the issue?**
 * [x] M.IM.Tokens

**Is this a new or an existing app?**

b. The app is in production and I haven't upgraded Microsoft.IdentityModel.*, but started seeing this issue. Specifically, when I attempted to update to version 7.0.0 or later.

**Repro**

```csharp
namespace test;

using Microsoft.IdentityModel.Tokens;

using System;

class Program
{
    static int Main(string[] args)
    {
        const string NotBase64UrlNorBase64 = "YWJ$";

        try
        {
            byte[] bytes = Base64UrlEncoder.DecodeBytes(NotBase64UrlNorBase64);
            Console.WriteLine("Unexpected successful decoding. Array length {0}", bytes.Length);
            foreach (byte b in bytes)
            {
                Console.Write("{0:X2} ", b);
            }

            string decodesString = Base64UrlEncoder.Decode(NotBase64UrlNorBase64);
            Console.WriteLine("Unexpected decoding into a string... IsNull? {0} Length = {1}", decodesString is null, decodesString?.Length ?? -1);

            return 1;

        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 0;
        }
    }
}

```

**Expected behavior**
`Base64UrlEncoder.DecodeBytes` and `Based64UrlEncoder.Decode` throw a `FormatException` indicating that there is an illegal charachter in the input:

```plain
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.UnsafeDecode(String str)
   at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.DecodeBytes(String str)
   at test.Program.Main(String[] args) in C:\src\playground\dnc\Program.cs:line 15
```

**Actual behavior**
An empty array/string is returned.

```plain
Unexpected successful decoding. Array length 0
Unexpected decoding into a string... IsNull? False Length = 0
```

This behavior change is a breaking change. I cannot find it listed in the [changelog](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/CHANGELOG.md), so I assume it is not an intentional breaking change. If returning empty is the new expected behavior, we can deal with that, but we would like confirmation that returning empty is the expected behavior.

**Possible solution**

Replace [the Debug.Assert on line 240 Base64UrlEncoder.cs](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f40dd9029c57167ce836bb4100a33dd5e1bf7d09/src/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.cs#L240) with an `if` check that throws on false.

That is, instead of this:

```csharp
bool converted = Convert.TryFromBase64Chars(source, bytesSpan, out int bytesWritten);
Debug.Assert(converted, "Expected TryFromBase64Chars to be successful");
byte[] result = bytesSpan.Slice(0, bytesWritten).ToArray();
```

Something more like this:

```csharp
bool converted = Convert.TryFromBase64Chars(source, bytesSpan, out int bytesWritten);
if (!converted) { throw new FormatException(...) };
byte[] result = bytesSpan.Slice(0, bytesWritten).ToArray();
```

**Additional context / logs / screenshots / links to code**

I believe this behavior change was introduced in commit [bc74959d (Reduce allocation with Base64UrlEncoder (#2162), 2023-07-28)](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/bc74959dada477f603da8126bf1c7f8be98bbbba).

**Comment by brentschmaltz** [comment]
@chwarr thanks, I agree this is a valid issue we should fix and add a test to protect against regression.
