### ISSUE TITLE
[Bug] Decryption of larger payload JWE fails with IDX10816 during deflation in DeflateCompressionProvider.cs

### ISSUE THREAD

**Issue by gjermund-stensrud** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2516]
**Which version of Microsoft.IdentityModel are you using?**
The program was originally running version 6.33.0 when it was working.
Microsoft.IdentityModel 7.4.0

**Where is the issue?**
 * [ ] M.IM.Tokens

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*
Below is code to reproduce the error.

```csharp
        using var encryptionKey = RSA.Create(3072); // public key for encryption, private key for decryption
        using var signingKey = RSA.Create(3072); // private key for signing, public key for validation

        var encryptionKid = "8524e3e6674e494f85c5c775dcd602c5";
        var signingKid = "29b4adf8bcc941dc8ce40a6d0227b6d3";

        var privateEncryptionKey = new RsaSecurityKey(encryptionKey) { KeyId = encryptionKid };
        var publicEncryptionKey = new RsaSecurityKey(encryptionKey.ExportParameters(false)) { KeyId = encryptionKid };
        var privateSigningKey = new RsaSecurityKey(signingKey) { KeyId = signingKid };
        var publicSigningKey = new RsaSecurityKey(signingKey.ExportParameters(false)) { KeyId = signingKid };

        // private key for signing
        var signingCredentials = new SigningCredentials(privateSigningKey, SecurityAlgorithms.RsaSha256);

        // public key for encryption
        var encryptingCredentials = new EncryptingCredentials(publicEncryptionKey, SecurityAlgorithms.RsaOAEP, SecurityAlgorithms.Aes256CbcHmacSha512);

        // Payload data
        var data = new List<Data>();
        for (var i = 0; i < 100000; i++) // Setting a lower number here will create a smaller payload that decrypts ok
        {
            data.Add(new Data { Prop1 = "Foo", Prop2 = 41 });
            data.Add(new Data { Prop1 = "Bar", Prop2 = 42 });
            data.Add(new Data { Prop1 = "Baz", Prop2 = 43 });
        }

        var payload = System.Text.Json.JsonSerializer.Serialize(data);

        // Encrypt
        var handler = new JsonWebTokenHandler();
        var token = handler.CreateToken(payload, signingCredentials, encryptingCredentials, "DEF");

        string? jsonPayload = null;

        // Decrypt
        var validationParameters = new TokenValidationParameters
        {
            ValidateAudience = false,
            ValidateLifetime = false,
            ValidateIssuer = false,

            // public key for signing
            IssuerSigningKey = publicSigningKey,

            // private key for encryption
            TokenDecryptionKey = privateEncryptionKey,

            TokenReader = (s, _) =>
            {
                var parts = s.Split('.');

                jsonPayload = Base64UrlEncoder.Decode(parts[1]);

                return new JwtSecurityToken(JwtHeader.Base64UrlDeserialize(parts[0]), new JwtPayload(), parts[0], parts[1], parts[2]);
            },
        };

        var tokenHandler = new JwtSecurityTokenHandler { MaximumTokenSizeInBytes = 1000000000 }; // Increasing max size does not work at this point
        var result = tokenHandler.ValidateToken(token, validationParameters, out _);


    class Data
    {
        public string? Prop1 { get; set; }
        public int Prop2 { get; set; }
    }
```

**Expected behavior**
Successful decryption and deflation with json payload extracted.

**Actual behavior**
Deflation fails with the following message:
Microsoft.IdentityModel.Tokens.SecurityTokenDecompressionFailedException: IDX10679: Failed to decompress using algorithm 'DEF'.
 ---> Microsoft.IdentityModel.Tokens.SecurityTokenDecompressionFailedException: IDX10816: Decompressing would result in a token with a size greater than allowed. Maximum size allowed: '1000000000'. 
at Microsoft.IdentityModel.Tokens.DeflateCompressionProvider.Decompress(Byte[] value)
at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.DecompressToken(Byte[] tokenBytes, String algorithm, Int32 maximumDeflateSize)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.DecryptJwtToken(SecurityToken securityToken, TokenValidationParameters validationParameters, JwtTokenDecryptionParameters decryptionParameters)
--- End of inner exception stack trace ---
    at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.DecryptJwtToken(SecurityToken securityToken, TokenValidationParameters validationParameters, JwtTokenDecryptionParameters decryptionParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.DecryptToken(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Hdir.HResept.IntegrationTests.HReseptTests.ShouldTestJwtDecryption() in C:\Utvikling\Hdir.HResept\src\Hdir.HResept.IntegrationTests\HReseptTests.cs:line 238
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

**Additional context / logs / screenshots / links to code**
When payload size increases it works to a point to increase the MaximumTokenSizeInBytes, but somwhere right before payloadSize=900000 it will always fail regardless of maximum token size.

**Comment by brentschmaltz** [comment]
@gjermund-stensrud sorry for the hassle.
Thanks for the repo.

**Comment by pmaytak** [comment]
While token is being decrypted, we check if the decrypted token will end up being larger than the max size value. So the error looks expected. However, there may be a bug where that's not respected. Thanks for the repro.

**Comment by pmaytak** [comment]
Looks like the issue is in the [DeflateCompressionProvider.Decompress](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/35cc68b38de33ebfa0ebb4ebe4f9453835f429dd/src/Microsoft.IdentityModel.Tokens/DeflateCompressionProvider.cs#L82) method. `StreamReader.Read` is not guaranteed to return bytes up to the maximum count specified. 

The fix is to read from the stream until all the bytes are read or the max deflate size is reached while counting the bytes read.
