### ISSUE TITLE
OpenIdConnectProtocolValidator.ValidateUserInfoResponse doesn't correctly accept JSON

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#283]
```
error   : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0017: Exception occurred while processing message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX10343: Unable to parse response from UserInfo endpoint: '{"tid":"cdc690f9-b6b8-4023-813a-bae7143d1f87","oid":"991fb93e-7400-47aa-bdaa-a5f5ea6b5669","upn":"testuser@Tratcheroutlook.onmicrosoft.com","sub":"KbB3DfyE3DEpxF-5a1b_vQzhr_6LjQFGwtBxkisZGXU","given_name":"test","family_name":"user","name":"test user"}' ---> System.ArgumentException: IDX10709: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken: jwtEncodedString' is not well formed: '{"tid":"cdc690f9-b6b8-4023-813a-bae7143d1f87","oid":"991fb93e-7400-47aa-bdaa-a5f5ea6b5669","upn":"testuser@Tratcheroutlook.onmicrosoft.com","sub":"KbB3DfyE3DEpxF-5a1b_vQzhr_6LjQFGwtBxkisZGXU","given_name":"test","family_name":"user","name":"test user"}'. The string needs to be in compact JSON format, which is of the form: '<Base64UrlEncodedHeader>.<Base64UrlEndcodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>'.
   at Microsoft.IdentityModel.Logging.LogHelper.Throw(String message, Type exceptionType, EventLevel logLevel, Exception innerException)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken..ctor(String jwtEncodedString)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateUserInfoResponse(OpenIdConnectProtocolValidationContext validationContext)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Logging.LogHelper.Throw(String message, Type exceptionType, EventLevel logLevel, Exception innerException)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateUserInfoResponse(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectHandler.<GetUserInformationAsync>d__17.MoveNext() in C:\git\Universe\Security\src\Microsoft.AspNet.Authentication.OpenIdConnect\OpenIdConnectHandler.cs:line 686
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleCodeOnlyFlow>d__14.MoveNext() in C:\git\Universe\Security\src\Microsoft.AspNet.Authentication.OpenIdConnect\OpenIdConnectHandler.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleAuthenticateAsync>d__13.MoveNext() in C:\git\Universe\Security\src\Microsoft.AspNet.Authentication.OpenIdConnect\OpenIdConnectHandler.cs:line 424
```

RE: https://github.com/aspnet/Security/issues/506

**Comment by brentschmaltz** [comment]
@tushargupta51 I pushed what I think a fix could look like to protocolValidator branch. It needs some testing. Can you take over and gets some tests in and push a new build. This blocks aspnet taking RC1 bits.

**Comment by tushargupta51** [comment]
@brentschmaltz will take a look

**Comment by tushargupta51** [comment]
@Tratcher @brentschmaltz merged the PR.
