### ISSUE TITLE
[Bug]  Could not load type 'ExceptionType' from assembly 'Microsoft.IdentityModel.Tokens

### ISSUE THREAD

**Issue by pantonis** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2945]
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

8.1.2

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

After updating from 8.0.2 to 8.1.2 and when calling 
```services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());``` in ```ConfigureServices``` in ```Startup.cs``` we receive the following exception

```
Unable to load one or more of the requested types.
Could not load type 'ExceptionType' from assembly 'Microsoft.IdentityModel.Tokens, Version=8.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.IdentityModel.Tokens.InternalTokenValidationResult' from assembly 'Microsoft.IdentityModel.Tokens, Version=8.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.IdentityModel.Tokens.InternalTokenValidationResult' from assembly 'Microsoft.IdentityModel.Tokens, Version=8.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.


   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass12_1.<AddAutoMapperClasses>b__6(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan, ServiceLifetime serviceLifetime)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Assembly[] assemblies)
   at MyService.Web.Web.Startup.ConfigureServices(IServiceCollection services) in C:\\Github\MyService\src\MyService.Web\Startup.cs:line 96
```

**Comment by pmaytak** [comment]
This may be related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2888 in 8.1.2 which reverts a change in the previous version.

Can you verify that all IdentityModel.* packages are of the same version - 8.1.2 (or better 8.2.0)?

**Comment by pantonis** [comment]
I updated to latest 8.2.0 and still the same bug
Below you can find the version of IdentityModel.* packages

Microsoft.IdentityModel.Abstractions.dll => 8.2.0.51101
Microsoft.IdentityModel.JsonWebTokens.dll => 8.0.2.50822
Microsoft.IdentityModel.Logging.dll => 8.2.0.51101
Microsoft.IdentityModel.Protocols.dll => 7.1.2.41121
Microsoft.IdentityModel.Protocols.OpenIdConnect.dll => 7.1.2.41121
Microsoft.IdentityModel.Tokens.dll => 8.2.0.51101

**Comment by pantonis** [comment]
anyone?

**Comment by pmaytak** [comment]
In the case above JsonWebTokens version should match Tokens package version (8.2.0). Ideally all IdentityModel.* packages should be of the same version. 

Seems like `AddAutoMapper` expects assemblies with AutoMapper profiles; so passing specific ones instead of loading all may prevent this issue.
