### ISSUE TITLE
AsymmetricSignatureProvider abusively disposes RSACryptoServiceProvider instances it doesn't own on .NET Desktop

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#477]
On .NET Desktop, signing or verifying a token more than once when the security key is a `RsaSecurityKey` results in an exception if the underlying algorithm instance is a `RSACryptoServiceProvider`:

```
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Security.Cryptography.Utils._GetKeyParameter(SafeKeyHandle hKey, UInt32 paramID)
   à System.Security.Cryptography.RSACryptoServiceProvider.get_KeySize()
   à Microsoft.IdentityModel.Tokens.RsaSecurityKey.get_KeySize()
   à Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.ValidateAsymmetricSecurityKeySize(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   à Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   à Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   à Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm)
   à System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   à System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
 `AsymmetricSignatureProvider.Dispose()`
```

This bug is likely caused by `Dispose()`, that disposes the underlying `RSACryptoServiceProvider` instance without ensuring it owns it: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L691

(it's likely the same as the one an ASOS user experienced last month when trying to use a CSP HSM)

**Comment by polita** [comment]
This looks a little tricky, because in some cases AsymmetricSignatureProvider does actually own _rsaCryptoServiceProvider, and in others, it gets it from the key passed in. Thanks for reporting, @PinpointTownes.

**Comment by brentschmaltz** [comment]
We should remember if we created the RSA, if not don't dispose.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L332

As a workaround, 

It should be possible to override CryptoProvider.ReleaseSignatureProvider or Dispose on the SignatureProvider.

**Comment by mbliesath** [comment]
I have a very similar issue when using the JwtBearerAuthentication middleware. The RSACryptoServiceProvider and other objects are disposed in the SigningCredentials after JwtSecurityTokenHandler.WriteToken() is called. So, the first request works, but any subsequent requests fail. This functionality worked great in RC2... but now WriteToken results in:

`System.ObjectDisposedException was unhandled by user code
  HResult=-2146232798
  Message=Safe handle has been closed
  ObjectName=""
  Source=mscorlib
  StackTrace:
       at System.Security.Cryptography.Utils._GetKeyParameter(SafeKeyHandle hKey, UInt32 paramID)
       at System.Security.Cryptography.RSACryptoServiceProvider.get_KeySize()
       at Microsoft.IdentityModel.Tokens.RsaSecurityKey.get_KeySize()
       at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.ValidateAsymmetricSecurityKeySize(SecurityKey key, String algorithm, Boolean willCreateSignatures)
       at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
       at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
       at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm)
       at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
       at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
       at Api.Controllers.TokenController.CreateToken(EmployeeSecurityRecord record, DateTime expires) in C:\SOURCE\Api\Procede.Excede.Api.Core\src\Api\Controllers\TokenController.cs:line 115
       at Api.Controllers.TokenController.Post(ResourceTokenRequest request) in C:\SOURCE\Api\Procede.Excede.Api.Core\src\Api\Controllers\TokenController.cs:line 35
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: `

I can't find any great documentation on proper usage of the JwtBearerAuthentication either. Any thoughts?

**Comment by brentschmaltz** [comment]
@mbliesath missed your comment. The library is disposing an rsa object it didn't create. A possible workaround it we get this fixed is based on JwtSecurityTokenHandler calls CryptoProviderFactory.ReleaseSignatureProvider after creating the signature. You can set your own CPF and override ReleaseSignatureProvider. RSP is in the call graph that will dispose the rsa.

**Comment by mbliesath** [comment]
@brentschmaltz Thanks for the advice. I will give that a shot... any time frame on the 5.0.1 release?

**Comment by brentschmaltz** [comment]
@PinpointTownes @mbliesath https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/518

**Comment by PinpointTownes** [comment]
@brentschmaltz thanks for fixing it!

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/518
