### ISSUE TITLE
Tests.CreateAndValidateTokens.CreateJWETokens fails

### ISSUE THREAD

**Issue by RussKie** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#573]
I just pulled down the latest dev branch, ran build.ps1 and got a test fail error

```
Test Name:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Test FullName:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Test Source:	D:\Development\IdentityModel\test\System.IdentityModel.Tokens.Jwt.Tests\CreateAndValidateTokens.cs : line 589
Test Outcome:	Failed
Test Duration:	0:00:00.048

Result1 Name:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Result1 Outcome:	Failed
Result1 Duration:	0:00:00.042
Result1 StackTrace:	
at Xunit.Assert.True(Nullable`1 condition, String userMessage)
   at Microsoft.IdentityModel.Tokens.Tests.ExpectedException.HandleError(String err, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\ExpectedException.cs:line 207
   at Microsoft.IdentityModel.Tokens.Tests.ExpectedException.ProcessException(Exception exception, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\ExpectedException.cs:line 114
   at System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens(String testId, String jweToken, TokenValidationParameters validationParameters, JwtPayload expectedPayload, ExpectedException ee) in D:\Development\IdentityModel\test\System.IdentityModel.Tokens.Jwt.Tests\CreateAndValidateTokens.cs:line 629
Result1 Message:	
exception != null, expectedException.TypeExpected == null.
exception: Xunit.Sdk.TrueException: CreateJWETokens: 


expectedPayload claim unique_name doesn't match in outerToken.Payload. Expected value: Jean-Sйbastien. Outer token value: Jean-Sebastien

Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
   at Microsoft.IdentityModel.Tokens.Tests.TestUtilities.AssertFailIfErrors(String testId, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\TestUtilities.cs:line 393
   at System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens(String testId, String jweToken, TokenValidationParameters validationParameters, JwtPayload expectedPayload, ExpectedException ee) in D:\Development\IdentityModel\test\System.IdentityModel.Tokens.Jwt.Tests\CreateAndValidateTokens.cs:line 625
Expected: True
Actual:   False
Result1 StandardOutput:
Result1 StandardError:

Result2 Name:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Result2 Outcome:	Failed
Result2 Duration:	0:00:00.001
Result2 StackTrace:	
at Xunit.Assert.True(Nullable`1 condition, String userMessage)
   at Microsoft.IdentityModel.Tokens.Tests.ExpectedException.HandleError(String err, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\ExpectedException.cs:line 207
   at Microsoft.IdentityModel.Tokens.Tests.ExpectedException.ProcessException(Exception exception, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\ExpectedException.cs:line 114
   at System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens(String testId, String jweToken, TokenValidationParameters validationParameters, JwtPayload expectedPayload, ExpectedException ee) in D:\Development\IdentityModel\test\System.IdentityModel.Tokens.Jwt.Tests\CreateAndValidateTokens.cs:line 629
Result2 Message:	
exception != null, expectedException.TypeExpected == null.
exception: Xunit.Sdk.TrueException: CreateJWETokens: 


expectedPayload claim unique_name doesn't match in outerToken.Payload. Expected value: Jean-Sйbastien. Outer token value: Jean-Sebastien

Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
   at Microsoft.IdentityModel.Tokens.Tests.TestUtilities.AssertFailIfErrors(String testId, List`1 errors) in D:\Development\IdentityModel\test\Microsoft.IdentityModel.Tokens.Tests\TestUtilities.cs:line 393
   at System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens(String testId, String jweToken, TokenValidationParameters validationParameters, JwtPayload expectedPayload, ExpectedException ee) in D:\Development\IdentityModel\test\System.IdentityModel.Tokens.Jwt.Tests\CreateAndValidateTokens.cs:line 625
Expected: True
Actual:   False
Result2 StandardOutput:
Result2 StandardError:

Result3 Name:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Result3 Outcome:	Passed
Result3 Duration:	0:00:00.002
Result3 StackTrace:
Result3 Message:
Result3 StandardOutput:
Result3 StandardError:

Result4 Name:	System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.CreateJWETokens
Result4 Outcome:	Passed
Result4 Duration:	0:00:00.003
Result4 StackTrace:
Result4 Message:
Result4 StandardOutput:
Result4 StandardError:

```

I think the data in the test claims may not account for non en-US default encodings or something like that...

![image](https://cloud.githubusercontent.com/assets/4403806/22859970/33dbfa24-f143-11e6-8c5c-569a03c3d338.png)
Also note `?` and other non-english chars (rendered as Cyrillic for me) in `new Claim("Turkish1", @"??I?i???зцЗЦ",`

**Comment by brentschmaltz** [comment]
@RussKie I am not seeing any errors in our nightly builds.

**Comment by RussKie** [comment]
I'll try it on few other machines and report back

**Comment by brentschmaltz** [comment]
@RussKie Please reopen if you are still seeing this issue.
