### ISSUE TITLE
Missing Newtonsoft.Json 9.0.1 dependency while calling the WriteToken method

### ISSUE THREAD

**Issue by aibars** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#701]
Hi,

I get a FileLoadException while trying to use the WriteToken exception:

FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 

Here's is the stack trace:
System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtPayload.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.get_EncodedPayload()
  at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)

**Comment by brentschmaltz** [comment]
@aibars it may be that there is a newer version of JSON.NET.  Have you tried adding a .Net binding redirect ?
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element

**Comment by aibars** [comment]
@brentschmaltz  yes, i tried adding:
<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="9.0.1" /> AND
<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
in the app.config file in the class library where I'm trying to use the library

**Comment by ChenYan98** [comment]
#765

**Comment by ritun85** [comment]
Hi ,
I am getting same kind of exception when I try to refer System.IdentityModel from openspan project  it throws me below error. As openspan itself uses Newtonsoft 5.X it does not allow 10.X. We dont have any option to provide binding redirect as there is no straight way to add config file in openspan. Please suggest


Source: "System.IdentityModel.Tokens.Jwt"
HResult: -2146233036

StackTrace Information
*********************************************
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtPayload.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.get_EncodedPayload()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at TokenGenerator.TokenGen.CreateToken()

3) Exception Information
*********************************************
Exception Type: System.IO.FileLoadException
Message: "Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Regards,
Ritun
