### ISSUE TITLE
XmlException when loading FederationMetadata.xml

### ISSUE THREAD

**Issue by KaareKarlsen** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#739]
When trying to read the FederationMetadata.xml from ADFS2016 the WsFederationMetadataSerializer throws an exception:

{Microsoft.IdentityModel.Xml.XmlReadException: IDX13000: Exception thrown while reading WsFedereationMetadata. Element 'EntityDescriptor'. Caught exception: 'System.Xml.XmlException: 'Element' is an invalid XmlNodeType. Line 1, position 60183.
   at System.Xml.XmlReader.ReadEndElement()
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadSecurityTokenEndpoint(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadSecurityTokenServiceTypeRoleDescriptor(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadEntityDescriptor(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadMetadata(XmlReader reader)'. ---> System.Xml.XmlException: 'Element' is an invalid XmlNodeType. Line 1, position 60183.
   at System.Xml.XmlReader.ReadEndElement()
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadSecurityTokenEndpoint(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadSecurityTokenServiceTypeRoleDescriptor(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadEntityDescriptor(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadMetadata(XmlReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMetadataSerializer.ReadMetadata(XmlReader reader)
   at Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfigurationRetriever.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()}

Debugging a bit further is seems like ReadSecurityTokenEndpoint doesn't handle that there could be a <metadata> tag after the <address> tag within the <endpointreference>

-<fed:SecurityTokenServiceEndpoint>
- <EndpointReference xmlns="http://www.w3.org/2005/08/addressing">
<Address>https://server/adfs/services/trust/2005/certificatemixed</Address>
-<Metadata>
-<Metadata xmlns="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
-<wsx:MetadataSection xmlns="" Dialect="http://schemas.xmlsoap.org/ws/2004/09/mex">
-<wsx:MetadataReference>
<Address xmlns="http://www.w3.org/2005/08/addressing">https://server/adfs/services/trust/mex</Address>
</wsx:MetadataReference>
</wsx:MetadataSection>
</Metadata>
</Metadata>
</EndpointReference>
</fed:SecurityTokenServiceEndpoint>

**Comment by brentschmaltz** [comment]
@KaareKarlsen thanks.
@lovemaths we will have to get together with our lab guys to obtains different versions of WSFedMetatada for ADFS v2, 3, 4.

**Comment by lovemaths** [comment]
committed the fix to dev.

**Comment by ashgadala** [comment]
@lovemaths How do we test this commit?

**Comment by lovemaths** [comment]
@ashgadala We haven't released it yet. If you want you can download this library, switch to dev branch, and add a unit test to test it.

**Comment by locutus80** [comment]
@lovemaths  Sorry, noob here, is there an updated nuget I can download with this fix please? Not 100% sure how I'd extract the bit I'd need from downloading the dev branch. ALternatively is there a timeframe you can share? Thanks

**Comment by brentschmaltz** [comment]
@locutus80 you can pick up packages from our nightlies here: https://www.myget.org/gallery/azureadwebstacknightly 

Currently these packages are not signed, but you can install these regkeys to bypass strong name.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/strongNameBypass.reg
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/strongNameBypass2.reg

**Comment by locutus80** [comment]
Thanks @lovemaths really appreciate that. I'll have to check VSTS and see if I can get it to use that package source and not check for signed packages

**Comment by reicher001** [comment]
Do we have a rough idea of when this will be released?  This will allow me to determine at which point it makes sense to try and get the package from the nightlies working or wait on the signed release.

**Comment by brentschmaltz** [comment]
@reicher001 we are in the final stages of shipping. We are feature complete, triaging bugs, finalizing tests and docs. It shouldn't be long.

**Comment by reicher001** [comment]
@brentschmaltz can you provide any details on what you are defining as "long"?  (days, weeks, months, ...)

**Comment by brentschmaltz** [comment]
weeks. we have validation and some perf to get through.

**Comment by leewadhams** [comment]
Hi, any further update on a potential release date for the package please?
