### ISSUE TITLE
FIPS compliant issue with System.IdentityModel.Tokens.Jwt, Version=4.0

### ISSUE THREAD

**Issue by lauthu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#753]
Hi, we are a team from Microsoft, and we are using  System.IdentityModel.Tokens.Jwt, Version=4.0, as below:
```
                var signcredentials = new SigningCredentials(
                        new InMemorySymmetricSecurityKey(System.Text.Encoding.Default.GetBytes(base64Secret)),
                        "http://www.w3.org/2001/04/xmldsig-more#hmac-sha256",
                        "http://www.w3.org/2001/04/xmlenc#sha256");
                SecurityToken token = new JwtSecurityToken(issuer, audience, claimIdentity.Claims, notbefore, expireon, signcredentials);

```
when we trying to validate this token using `JwtSecurityTokenHandler.ValidateToken(string, TokenValidationParameters, out SecurityToken)`, we encoutered this FIPS uncompiant error:
```
'System.InvalidOperationException: IDX10632: SymmetricSecurityKey.GetKeyedHashAlgorithm( 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256' ) threw an exception.
SymmetricSecurityKey: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256', check to make sure the SignatureAlgorithm is supported.
Exception: 'System.InvalidOperationException: The algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256' was used with Federal Information Processing Standards (FIPS) mode enabled, but is not FIPS compatible. 
   at System.IdentityModel.CryptoHelper.CreateKeyedHashAlgorithm(Byte[] key, String algorithm)
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm)'. ---> System.InvalidOperationException: The algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256' was used with Federal Information Processing Standards (FIPS) mode enabled, but is not FIPS compatible. 
   at System.IdentityModel.CryptoHelper.CreateKeyedHashAlgorithm(Byte[] key, String algorithm)
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SymmetricSecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
```

Does this mean this library's implementation not FIPS compliant? Does new version of System.IdentityModel.Tokens.Jwt fix this problem?

**Comment by brentschmaltz** [comment]
@lauthu The 4.x version of IdentityModel layers of System.IdentityModel. You can CryptoConfig. If that doesn't work, then  reopen this issue and then we can look for a solution.
