### ISSUE TITLE
Saml2SecurityTokenReadException from middleware when it processes RequestSecurityTokenResponse from STS(Okta) at /signin-wsfed endpoint

### ISSUE THREAD

**Issue by mikepolyak** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#881]
Hello,
We have ASP.NET Core v 2.0.1 MVC application that uses  Microsoft.AspNetCore.Authentication.WsFederation middleware (https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation) to authenticate with external security token service (Okta).  Middleware is wired as follows and starts up without issues. However after user has been authenticated in Okta and response is sent back to application on /signin-wsfed endpoint for middleware to process, the following Saml2SecurityTokenReadException occurs.

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/signin-wsfed application/x-www-form-urlencoded 9032
fail: Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler[3]
      Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenReadException: IDX13102: Exception thrown while reading '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]' for Saml2SecurityToken. Inner exception: 'Microsoft.IdentityModel.Xml.XmlReadException: IDX30016: Exception thrown while reading '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'. See inner exception for more details. ---> System.Xml.XmlException: End element 'Transform' from namespace 'http://www.w3.org/2000/09/xmldsig#' expected. Found element 'ec:InclusiveNamespaces' from namespace 'http://www.w3.org/2001/10/xml-exc-c14n#'. Line 1, position 285.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlExceptionHelper.ThrowEndElementExpected(XmlDictionaryReader reader, String localName, String ns)
   at System.Xml.XmlBaseReader.ReadEndElement()
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadTransforms(XmlReader reader, Reference reference)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadTransforms(XmlReader reader, Reference reference)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadReference(XmlReader reader)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadSignedInfo(XmlReader reader)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadSignature(XmlReader reader)
   at Microsoft.IdentityModel.Xml.EnvelopedSignatureReader.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.XmlDictionaryReader.ReadElementContentAsString()
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadNameIdType(XmlDictionaryReader reader)'. ---> Microsoft.IdentityModel.Xml.XmlReadException: IDX30016: Exception thrown while reading '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'. See inner exception for more details. ---> System.Xml.XmlException: End element 'Transform' from namespace 'http://www.w3.org/2000/09/xmldsig#' expected. Found element 'ec:InclusiveNamespaces' from namespace 'http://www.w3.org/2001/10/xml-exc-c14n#'. Line 1, position 285.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlExceptionHelper.ThrowEndElementExpected(XmlDictionaryReader reader, String localName, String ns)
   at System.Xml.XmlBaseReader.ReadEndElement()
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadTransforms(XmlReader reader, Reference reference)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadTransforms(XmlReader reader, Reference reference)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadReference(XmlReader reader)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadSignedInfo(XmlReader reader)
   at Microsoft.IdentityModel.Xml.DSigSerializer.ReadSignature(XmlReader reader)
   at Microsoft.IdentityModel.Xml.EnvelopedSignatureReader.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.XmlDictionaryReader.ReadElementContentAsString()
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadNameIdType(XmlDictionaryReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadNameIdType(XmlDictionaryReader reader)
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadIssuer(XmlDictionaryReader reader)
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadAssertion(XmlReader reader)
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ReadSaml2Token(String token)
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleRemoteAuthenticateAsync>d__9.MoveNext()
 
Here is how middleware is wired up

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddTcis();
            services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultSignInScheme = Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;

                })
                .AddWsFederation(options =>
                {
                    options.Wtrealm = Configuration["okta:wsfederation:Wtrealm"];
                    options.MetadataAddress = Configuration["okta:wsfederation:MetadataAddress"];
                    options.RequireHttpsMetadata = false;
                    options.SaveTokens = true;
                    options.TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidAudience = Configuration["okta:wsfederation:ValidAudience"]
                    };
                })
                .AddCookie();

            services.AddMvc()
                .AddJsonOptions(options =>
                    {
                        options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                        options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                    }
                );
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });
            });
        }
    }
Thank you
Mike

**Comment by ChenYan98** [comment]
I went through the code, and it seemed to me that the library only support InclusiveNamespaces without "ec:" namespace.

**Comment by brentschmaltz** [comment]
@mikepolyak this is a bug, we will push a PR soon for testing in our nightlies. Our next release should have this fixed.

**Comment by mikepolyak** [comment]
We have upgraded Microsoft.AspNetCore.Authentication.WsFederation to the latest 2.0.3 version, but unfortunately behavior is the same - System.Xml.XmlException: End element 'Transform' from namespace 'http://www.w3.org/2000/09/xmldsig#' expected. Found element 'ec:InclusiveNamespaces' from namespace 'http://www.w3.org/2001/10/xml-exc-c14n#'. Line 1, position 286.

**Comment by brentschmaltz** [comment]
@mikepolyak we have this PR:  https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/890 to fix the issue. I expect an official release within a month.

**Comment by brentschmaltz** [comment]
@mikepolyak we just merged this into dev. Will be in next nightlies, try it out if you can.
