### ISSUE TITLE
JsonWebSecurityTokenHandler raise System.NullReferenceException on empty payload

### ISSUE THREAD

**Issue by ycrumeyrolle** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#981]
Hi, 

I have a `NullReferenceException` when try to validate an empty JWT like `eyJhbGciOiJIUzI1NiJ9.e30.ZRrHA1JJJW8opsbCGfG_HACGpVUMN_a9IV7pAx_Zmeo` / `{"alg": "HS256"}.{}`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.get_Audiences() in C:\agent2\_work\15\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebToken.cs:line 113
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateTokenPayload(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters) in C:\agent2\_work\15\s\src\Microsoft.IdentityModel.JsonWebTokens\JsonWebTokenHandler.cs:line 414
   at JsonWebToken.Performance.ValidateToken.Wilson2(String token) in C:\dev\git\Jwt\test\Benchmarks\ValidateToken.cs:line 62
```

Sample of the code can be found at https://github.com/ycrumeyrolle/Jwt/blob/dev/test/Benchmarks/ValidateToken.cs#L62
 
The package is Microsoft.IdentityModel.JsonWebTokens v5.2.4

**Comment by brentschmaltz** [comment]
@ycrumeyrolle sorry for this. We are addressing parts of this in a PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/976

Will fix this up.
